/**
 * Universal Export Center Engine
 * Generates client-side downloadable bundles across PDF (Print HTML),
 * Word Spec (Markdown/Docx), Excel/CSV Data, OpenAPI 3.1 JSON, and PostgreSQL 16 DDL
 * dynamically tailored to any problem statement / domain blueprint.
 */
import { getDatabaseBlueprint } from "./database-data";
import { getRoadmapForWorkspace } from "./planning-data";
import { getRoiBlueprint } from "./roi-data";
import { saveAndShareFile } from "./native-bridge";

export function generateOpenApiJson(workspaceContext?: any): string {
  const dbBlueprint = getDatabaseBlueprint(workspaceContext);
  const name = workspaceContext?.businessName || workspaceContext?.name || dbBlueprint.domainTitle;

  const paths: Record<string, any> = {};

  dbBlueprint.apiSpecifications.forEach((api) => {
    const methodLower = api.method.toLowerCase();
    if (!paths[api.path]) {
      paths[api.path] = {};
    }
    paths[api.path][methodLower] = {
      summary: api.summary,
      tags: [api.category],
      security: [{ BearerAuth: [] }],
      responses: {
        "200": {
          description: "Successful response",
          content: {
            "application/json": {
              example: JSON.parse(api.responseBody || "{}"),
            },
          },
        },
      },
    };
    if (api.requestBody) {
      try {
        paths[api.path][methodLower].requestBody = {
          required: true,
          content: {
            "application/json": {
              example: JSON.parse(api.requestBody),
            },
          },
        };
      } catch {}
    }
  });

  return JSON.stringify(
    {
      openapi: "3.1.0",
      info: {
        title: `${name} — RESTful API Specification`,
        version: "1.1.0",
        description: `Derivation of technical architecture and database models generated by BizzMitra-AI for ${name}.`,
      },
      servers: [
        { url: "https://api.bizzmitra.enterprise/v1", description: "Production Gateway" },
        { url: "http://localhost:8080/v1", description: "Local Development" },
      ],
      paths,
      components: {
        securitySchemes: {
          BearerAuth: {
            type: "http",
            scheme: "bearer",
            bearerFormat: "JWT",
          },
        },
      },
    },
    null,
    2
  );
}

export function generatePostgreSqlDdl(workspaceContext?: any): string {
  const dbBlueprint = getDatabaseBlueprint(workspaceContext);
  return dbBlueprint.ddlSchema;
}

export function generateTechnicalSpecMarkdown(workspaceContext?: any): string {
  const roadmap = getRoadmapForWorkspace(workspaceContext);
  const roi = getRoiBlueprint(workspaceContext);
  const dbBlueprint = getDatabaseBlueprint(workspaceContext);
  const name = workspaceContext?.businessName || workspaceContext?.name || roadmap.scenarioName;

  return `# ${name} — Technical Transformation Specification (v1.3)

> **Generated by BizzMitra-AI Universal Export Center** on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  
> **Status:** APPROVED FOR IMPLEMENTATION  
> **Governance Sign-Off:** Solution Architect, Operations Lead, Product Delivery Lead, Security & Compliance

---

## 1. Executive Summary
${roadmap.executiveSummary}

- **Delivery Timeline:** ${roadmap.targetTimelineWeeks} Calendar Weeks (${roadmap.totalPersonDays} Person-Days across 3 Sprints)
- **Target Go-Live Readiness:** ${roadmap.estimatedGoLive}
- **Confidence Rating:** ${roadmap.confidenceScore}% (Validated Architecture)
- **Database Entities:** ${dbBlueprint.tables.length} Normalized Tables (PostgreSQL 16+ RLS)
- **API Endpoints:** ${dbBlueprint.apiSpecifications.length} RESTful Routes (OpenAPI 3.1)

---

## 2. Core Solution Architecture & Topology
1. **Interactive Operational Prototype (USP #1):** Live responsive application with stage transitions, filtering, search, and activity triggers.
2. **Solution Studio Runtime Customizer (USP #2):** Dynamic schema extension enabling field additions and versioned AI state regeneration.
3. **Multi-Tenant Relational Tier:** Isolated tenant row-level policies (\`org_id\`) with column-level encryption for sensitive attributes.
4. **Asynchronous Event Processing:** Redis 7 and BullMQ task workers ensuring non-blocking execution across external integrations.

---

## 3. Database Entities & Schemas (${dbBlueprint.tables.length} Tables)
${dbBlueprint.tables
  .map(
    (t) =>
      `### Table: \`${t.name}\` (${t.category})\n${t.description}\n\n| Column | Type | Constraints | Description |\n|---|---|---|---|\n${t.columns
        .map((c) => `| \`${c.name}\` | \`${c.type}\` | ${c.constraints} | ${c.description} |`)
        .join("\n")}`
  )
  .join("\n\n")}

---

## 4. ${roadmap.targetTimelineWeeks}-Week Delivery Sprints
${roadmap.phases
  .map(
    (p) =>
      `### Phase ${p.phaseNumber}: ${p.name} (${p.durationWeeks}) — ${p.codename}\n**Objective:** ${p.objective}\n\n**Milestones:**\n${p.milestones
        .map((m) => `- [${m.completed ? "X" : " "}] **${m.title}** (${m.effortDays}d, ${m.category}): ${m.deliverable}`)
        .join("\n")}\n\n**Resourcing Squad:**\n${p.teamResourcing.map((r) => `- ${r.role} (${r.fte} FTE): ${r.responsibilities}`).join("\n")}`
  )
  .join("\n\n")}

---

## 5. Enterprise Risk Register & Proactive Mitigations
${roadmap.riskRegister
  .map(
    (r) =>
      `- **${r.title}** [${r.category} | Likelihood: ${r.likelihood} | Impact: ${r.impact}]\n  - *Consequence:* ${r.consequence}\n  - *Mitigation:* ${r.mitigationStrategy}\n  - *Owner:* ${r.owner}`
  )
  .join("\n\n")}

---

## 6. Financial ROI & Readiness Benchmark
- **Operational Payback:** ${roi.defaultInputs ? "Rapid Break-Even" : "Accelerated Payback"}
- **Key Operational Delta:**
${roi.benchmarks.map((b) => `  - **${b.metric}:** Before ${b.before} ➔ After ${b.after} (\`${b.change}\`)`).join("\n")}
`;
}

export function generateDomainCsv(workspaceContext?: any): string {
  const dbBlueprint = getDatabaseBlueprint(workspaceContext);
  const domainId = dbBlueprint.domainId;

  if (domainId === "solar") {
    return `Inverter_ID,Plant_Zone,Active_Power_kW,DC_Voltage_V,AC_Current_A,Thermal_Temp_C,Status,Curtailment_Limit_kW
INV-01-A,North Array,248.5,842.0,295.1,48.2,Optimal,250.0
INV-01-B,North Array,246.1,839.5,293.0,49.1,Optimal,250.0
INV-02-A,East Array,212.0,795.0,266.6,56.8,Clipping_Alert,210.0
INV-02-B,East Array,0.0,0.0,0.0,24.0,Offline_Maintenance,0.0
INV-03-A,Central Array,249.0,845.0,294.6,47.9,Optimal,250.0`;
  }

  if (domainId === "healthcare") {
    return `Specimen_Barcode,Patient_MRN,Test_Panel,Result_Value,Reference_Range,Analyzer_ID,Panic_Flag,Status
BAR-99012,MRN-10492,Serum Potassium,6.8 mmol/L,3.5 - 5.0 mmol/L,CHEM-ROCHE-01,CRITICAL_HIGH,Escalated_Doctor_Alerted
BAR-99013,MRN-88214,Hemoglobin,14.2 g/dL,13.0 - 17.0 g/dL,HEM-SYSMEX-02,NORMAL,Verified_Released
BAR-99014,MRN-33129,Platelet Count,28 10^3/uL,150 - 450 10^3/uL,HEM-SYSMEX-02,CRITICAL_LOW,Delta_Check_Triggered
BAR-99015,MRN-55018,Fasting Glucose,96 mg/dL,70 - 99 mg/dL,CHEM-ROCHE-01,NORMAL,Verified_Released
BAR-99016,MRN-77401,Troponin-I,1.85 ng/mL,< 0.04 ng/mL,IMMUNO-ARCH-03,CRITICAL_HIGH,Escalated_Phone_Logged`;
  }

  if (domainId === "logistics") {
    return `Consignment_ID,Vehicle_Unit,Driver_Name,Origin_Hub,Destination_Hub,Payload_Weight_Kg,Status,ETA_Compliance
SHP-8821,TRK-104,Harpreet Singh,Delhi Central Hub,Jaipur Logistics Park,14200,In_Transit_On_Time,98.5%
SHP-8822,TRK-108,Ramesh Sharma,Mumbai Port Terminal,Pune Industrial Zone,18500,Geofence_Arrived,100%
SHP-8823,TRK-112,Vikram Yadav,Bangalore Hub,Chennai Container Terminal,12000,VRP_Rerouted_Weather,94.2%
SHP-8824,TRK-119,Gurpreet Gill,Ahmedabad Warehouse,Surat Textile Zone,8500,In_Transit_On_Time,99.1%
SHP-8825,TRK-125,Suresh Nair,Kochi Freight Depot,Coimbatore Hub,16400,Delayed_Traffic_Flagged,88.0%`;
  }

  if (domainId === "fintech") {
    return `Application_ID,Borrower_Name,Loan_Type,CIBIL_Score,Requested_Amount_INR,Sanctioned_Amount_INR,Status,eNACH_Active
APP-2026-001,Aarav Verma,MSME Working Capital,782,1500000,1500000,Approved_Disbursed,Yes
APP-2026-002,Pooja Patel,Personal Loan,814,500000,500000,Approved_Disbursed,Yes
APP-2026-003,Rohan Deshmukh,Business Expansion,645,2500000,0,Rejected_Low_Bureau,No
APP-2026-004,Ananya Iyer,Equipment Finance,740,800000,800000,Underwriting_Review,Pending
APP-2026-005,Karan Gupta,Invoice Discounting,795,1200000,1200000,Approved_eSign_Complete,Yes`;
  }

  // HR / Default
  return `Candidate_ID,Full_Name,Applied_Role,Pipeline_Stage,Experience_Years,Rating,Custom_LinkedIn_URL
CAN-001,Aarav Patel,Senior React Engineer,Interview,6.5,4.8,https://linkedin.com/in/aarav-patel
CAN-002,Meera Iyer,Fullstack Node Architect,Offer,8.0,4.9,https://linkedin.com/in/meera-iyer
CAN-003,Rohan Verma,DevOps & Cloud Engineer,Screening,4.5,4.2,https://linkedin.com/in/rohan-v
CAN-004,Ananya Sen,HR Operations Specialist,Interview,5.0,4.6,https://linkedin.com/in/ananya-sen
CAN-005,Vikram Sengupta,Systems Architect,Screening,9.2,4.7,https://linkedin.com/in/vikram-s`;
}

export function downloadFile(filename: string, content: string, mimeType: string): void {
  if (typeof window === "undefined") return;
  void saveAndShareFile(filename, content, mimeType);
}
