/**
 * Universal Export Center Engine
 * Generates client-side downloadable bundles across PDF (Print HTML),
 * Word Spec (Markdown/Docx), Excel/CSV Data, OpenAPI 3.1 JSON, and PostgreSQL 16 DDL.
 */

export function generateOpenApiJson(workspaceName = "TalentCraft HR Consultancy"): string {
  return JSON.stringify(
    {
      openapi: "3.1.0",
      info: {
        title: `${workspaceName} — API Specification`,
        version: "1.1.0",
        description: "Generated by BizzMitra-AI Universal Export Center.",
      },
      servers: [
        { url: "https://api.talentcraft.io/v1", description: "Production Gateway" },
        { url: "http://localhost:8080/v1", description: "Local Development" },
      ],
      paths: {
        "/candidates": {
          get: {
            summary: "List candidates with stage and attribute filters",
            parameters: [
              { name: "stage", in: "query", schema: { type: "string", enum: ["screening", "interview", "offer", "rejected"] } },
              { name: "search", in: "query", schema: { type: "string" } },
            ],
            responses: {
              "200": {
                description: "Filtered list of talent profiles",
                content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Candidate" } } } },
              },
            },
          },
          post: {
            summary: "Create new candidate profile",
            requestBody: {
              required: true,
              content: { "application/json": { schema: { $ref: "#/components/schemas/CandidateInput" } } },
            },
            responses: {
              "201": { description: "Candidate created successfully" },
            },
          },
        },
        "/candidates/{id}/stage": {
          patch: {
            summary: "Transition candidate pipeline stage",
            parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
            requestBody: {
              required: true,
              content: { "application/json": { schema: { type: "object", properties: { stage: { type: "string" }, notes: { type: "string" } } } } },
            },
            responses: {
              "200": { description: "Stage updated and event broadcasted" },
            },
          },
        },
        "/attendance/punch": {
          post: {
            summary: "Record consultant punch in or out timestamp",
            requestBody: {
              required: true,
              content: { "application/json": { schema: { type: "object", properties: { type: { type: "string", enum: ["in", "out"] }, location: { type: "string" } } } } },
            },
            responses: {
              "200": { description: "Punch recorded with geolocation" },
            },
          },
        },
      },
      components: {
        schemas: {
          Candidate: {
            type: "object",
            properties: {
              id: { type: "string", format: "uuid" },
              name: { type: "string" },
              email: { type: "string", format: "email" },
              role: { type: "string" },
              experienceYears: { type: "number" },
              stage: { type: "string" },
              rating: { type: "number" },
              customFields: { type: "object", additionalProperties: true },
            },
          },
          CandidateInput: {
            type: "object",
            required: ["name", "email", "role"],
            properties: {
              name: { type: "string" },
              email: { type: "string", format: "email" },
              role: { type: "string" },
              experienceYears: { type: "number" },
            },
          },
        },
      },
    },
    null,
    2
  );
}

export function generatePostgreSqlDdl(): string {
  return `-- ====================================================================
-- BizzMitra-AI: Multi-Tenant PostgreSQL 16+ Production DDL Schema
-- Workspace: TalentCraft HR Consultancy (v1.1)
-- ====================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Organizations (Tenants)
CREATE TABLE organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    industry VARCHAR(100) NOT NULL DEFAULT 'HR & Recruitment',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Candidates
CREATE TABLE candidates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    role VARCHAR(150) NOT NULL,
    stage VARCHAR(50) NOT NULL DEFAULT 'screening' CHECK (stage IN ('screening', 'interview', 'offer', 'rejected')),
    experience_years NUMERIC(4,1) NOT NULL DEFAULT 0.0,
    rating NUMERIC(2,1) NOT NULL DEFAULT 4.0,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    custom_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- GIN Index for rapid JSONB querying across custom attributes (e.g. LinkedIn URL)
CREATE INDEX idx_candidates_custom_attributes ON candidates USING gin (custom_attributes);
CREATE INDEX idx_candidates_stage ON candidates (organization_id, stage);

-- Attendance Punches
CREATE TABLE attendance_punches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    consultant_name VARCHAR(255) NOT NULL,
    punch_type VARCHAR(20) NOT NULL CHECK (punch_type IN ('in', 'out')),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    location_tag VARCHAR(255) DEFAULT 'Office HQ'
);

-- Enable Row Level Security (RLS)
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_punches ENABLE ROW LEVEL SECURITY;

-- Tenant Isolation Policies
CREATE POLICY tenant_isolation_candidates ON candidates
    FOR ALL
    USING (organization_id = (auth.jwt() ->> 'organization_id')::uuid);

CREATE POLICY tenant_isolation_attendance ON attendance_punches
    FOR ALL
    USING (organization_id = (auth.jwt() ->> 'organization_id')::uuid);
`;
}

export function generateTechnicalSpecMarkdown(workspaceName = "TalentCraft HR Consultancy"): string {
  return `# ${workspaceName} — Technical Transformation Specification (v1.3)

> **Generated by BizzMitra-AI** on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  
> **Status:** APPROVED FOR IMPLEMENTATION  
> **Governance Sign-Off:** Solution Architect, HR Ops Lead, Product Delivery Lead, Security & Compliance

---

## 1. Executive Summary
TalentCraft is modernizing its boutique recruitment operations from error-prone spreadsheets into a centralized, cloud-native **Talent Acquisition & Consultant Attendance Platform**.

- **Delivery Timeline:** 9 Calendar Weeks (68 Person-Days across 3 Sprints)
- **Net Annual Benefit:** ₹32,30,000 / year (3,240 Recruiter Admin Hours Reclaimed)
- **Payback Period:** 2.4 Months (Full Break-Even in Q1)
- **Target Velocity:** 28 Days hiring turnaround accelerated to 9 Days (-68%)

---

## 2. Recommended Solution Suite
1. **Core ATS Pipeline (Workable USP #1):** Interactive candidate grid, stage progression (Screening → Interview → Offer → Rejected), full-text search, and automated timesheet punch clock.
2. **Client Requisition Portal:** Self-serve client portal enabling corporate hiring managers to post openings and review shortlists.
3. **Automated Interview Coordination:** Calendar sync and WhatsApp notifications reducing candidate no-show rates by 78%.
4. **AI Talent Matching:** Semantic vector resume indexing matching applicants to open job requisitions.

---

## 3. Technology Architecture
- **Presentation:** React 19 SPA + TanStack Router + Tailwind CSS v4
- **Edge Gateway:** Cloudflare Workers with JWT authentication & rate limiting
- **Backend Services:** Node.js & Go microservices (Docker containers on AWS ECS)
- **Database:** PostgreSQL 16+ with Row Level Security (RLS) for multi-tenant isolation
- **Caching & Queues:** Redis 7 Cluster & BullMQ for asynchronous resume extraction

---

## 4. 9-Week Delivery Plan
- **Phase 1: Foundation Sprint (Weeks 1–3, 21 Person-Days):** PostgreSQL schema, Core ATS Pipeline, Attendance punch clock.
- **Phase 2: Coordination Sprint (Weeks 4–6, 23 Person-Days):** Client portal, WhatsApp Business API webhooks, Calendar sync.
- **Phase 3: Intelligence Sprint (Weeks 7–9, 24 Person-Days):** AI resume parser, semantic matcher, executive analytics, and cutover.

---

## 5. Risk Mitigation Register
- **Recruiter Adoption:** Mitigated via 1-click CSV export and Excel-like keyboard shortcuts.
- **Resume Parsing Variance:** Mitigated via human-in-the-loop candidate review cards.
- **DPDP Act Compliance:** Mitigated via automated 180-day resume retention purge policies.
`;
}

import { saveAndShareFile } from "./native-bridge";

export function downloadFile(filename: string, content: string, mimeType: string): void {
  if (typeof window === "undefined") return;
  void saveAndShareFile(filename, content, mimeType);
}
