import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Sparkles, Layout, Compass } from "lucide-react";

import { AppShell } from "@/components/AppShell";
import { ArtifactHeader } from "@/components/ArtifactHeader";
import { GenerationSequence } from "@/components/GenerationSequence";
import { Mermaid } from "@/components/Mermaid";
import { GENERATION_STEPS, generateArtifact } from "@/lib/ai/generate-artifact";
import { getWireframeBlueprint } from "@/lib/wireframes-data";
import { WireframeVisualizer } from "@/components/WireframeVisualizer";

export const Route = createFileRoute("/workspace/wireframes")({
  head: () => ({
    meta: [
      { title: "AI UX Designer & Wireframes — BizzMitra-AI" },
      {
        name: "description",
        content:
          "Interactive screen concepts, responsive wireframes, and navigation flows generated by the AI UX Designer.",
      },
      { property: "og:title", content: "AI UX Designer & Wireframes — BizzMitra-AI" },
      {
        property: "og:description",
        content: "Interactive wireframes and navigation flow concepts.",
      },
    ],
  }),
  component: WireframesPage,
});

function WireframesPage() {
  const [workspaceContext, setWorkspaceContext] = useState<{
    businessName: string;
    industry: string;
    problemStatement?: string;
  }>({
    businessName: "TalentCraft HR Consultancy",
    industry: "HR & Recruitment Services",
    problemStatement: "",
  });

  useEffect(() => {
    try {
      const raw = window.localStorage.getItem("bizzmitra.workspaceContext");
      if (raw) {
        const parsed = JSON.parse(raw);
        setWorkspaceContext({
          businessName: parsed.businessName || "TalentCraft HR Consultancy",
          industry: parsed.industry || "HR & Recruitment Services",
          problemStatement: parsed.problemStatement || "",
        });
      }
    } catch {}
  }, []);

  const blueprint = getWireframeBlueprint(workspaceContext);

  return (
    <AppShell>
      <ArtifactHeader
        id="wireframes"
        kicker="Step 06 • AI UX Designer"
        title="Interactive Wireframes & Screen Concepts"
      />

      {/* Blueprint Context Banner */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-2 rounded-xl border border-primary/20 bg-primary/5 px-4 py-2.5 text-xs">
        <div className="flex items-center gap-2">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          <span className="text-muted-foreground">Tailored Wireframes For:</span>
          <span className="font-bold text-foreground">{workspaceContext.businessName}</span>
          <span className="rounded-full bg-primary/10 px-2 py-0.5 font-medium text-primary">
            {workspaceContext.industry}
          </span>
        </div>
        <Link to="/workspace/process" className="font-medium text-primary hover:underline">
          View BPMN Process Intelligence →
        </Link>
      </div>

      <GenerationSequence steps={GENERATION_STEPS.ux} run={() => generateArtifact("ux")}>
        <div className="space-y-8">
          {/* Main Feature: Interactive Multi-Device Wireframe Visualizer */}
          <div>
            <WireframeVisualizer blueprint={blueprint} />
          </div>

          {/* Screen Concept Inventory */}
          <div className="neu p-6 space-y-4">
            <div className="flex items-center gap-2 border-b border-border/60 pb-3">
              <Layout className="size-4 text-primary" />
              <h3 className="font-display text-base font-bold text-foreground">
                Screen Architecture & Component Inventory
              </h3>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {blueprint.inventory.map((w) => (
                <div
                  key={w.id}
                  className="neu-sm p-4 rounded-xl border border-border/70 bg-surface/50 space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-mono text-primary uppercase font-bold">
                      ID: {w.id}
                    </span>
                    <span className="size-2 rounded-full bg-emerald-500" />
                  </div>
                  <p className="text-xs font-bold text-foreground">{w.name}</p>
                  <p className="text-[11px] text-muted-foreground leading-relaxed">{w.note}</p>
                </div>
              ))}
            </div>
          </div>

          {/* User Journey & Navigation Flow Diagram */}
          <div className="neu overflow-x-auto p-6 space-y-3">
            <div className="flex items-center gap-2 border-b border-border/60 pb-3">
              <Compass className="size-4 text-primary" />
              <div>
                <h3 className="font-display text-base font-bold text-foreground">
                  User Journey & Screen Navigation Flow
                </h3>
                <p className="text-xs text-muted-foreground">
                  End-to-end navigational routing between screens, core workflows, and administration portals.
                </p>
              </div>
            </div>
            <div className="mt-4">
              <Mermaid key={blueprint.domainId} chart={blueprint.navFlowDiagram} />
            </div>
          </div>
        </div>
      </GenerationSequence>
    </AppShell>
  );
}
