import { createFileRoute } from "@tanstack/react-router";
import { AnimatePresence, motion } from "motion/react";
import {
  Check,
  ChevronDown,
  Clock,
  Download,
  ExternalLink,
  Filter,
  Plus,
  RefreshCw,
  Search,
  Sliders,
  Sparkles,
  Star,
  Tag,
  Timer,
  Trash2,
  Users,
  Wand2,
  X,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { AppShell } from "@/components/AppShell";
import { ArtifactHeader } from "@/components/ArtifactHeader";
import { GenerationSequence } from "@/components/GenerationSequence";
import { SolutionStudioDrawer } from "@/components/SolutionStudioDrawer";
import { Stagger, StaggerItem } from "@/components/motion/primitives";
import { GENERATION_STEPS, generateArtifact } from "@/lib/ai/generate-artifact";
import {
  HR_ATTENDANCE_LOG,
  HR_CRM_CANDIDATES,
  type AttendanceEntry,
  type CRMCandidate,
} from "@/lib/demo-data";
import {
  THEME_ACCENTS,
  loadStudioSettings,
  saveStudioSettings,
  type CustomField,
  type StudioSettings,
} from "@/lib/solution-studio";
import { cn } from "@/lib/utils";
import { saveAndShareFile } from "@/lib/native-bridge";
import { useStageGate } from "@/lib/workspace-stage-gate";

export const Route = createFileRoute("/workspace/solution_/crm")({
  head: () => ({
    meta: [
      { title: "Interactive Prototype CRM — BizzMitra-AI" },
      {
        name: "description",
        content:
          "Fully interactive live CRM and workflow prototype generated from your business solution with pipeline tracking, filters, CSV export, and attendance engine.",
      },
      { property: "og:title", content: "Interactive Prototype CRM — BizzMitra-AI" },
      {
        property: "og:description",
        content: "A live, runnable operational CRM generated by BizzMitra's AI Solution Engine.",
      },
    ],
  }),
  component: CRMPage,
});

/* ───────────── Domain-Adaptive CRM Engine ───────────── */

interface DomainConfig {
  domainType: string;
  title: string;
  entityName: string;
  entityPlural: string;
  roleLabel: string;
  stages: string[];
  stageColors: Record<string, string>;
  defaultRecords: CRMCandidate[];
  attendanceTitle: string;
}

function getDomainConfig(context?: { businessName?: string; industry?: string; problemStatement?: string } | null): DomainConfig {
  const text = `${context?.businessName ?? ""} ${context?.industry ?? ""} ${context?.problemStatement ?? ""}`.toLowerCase();

  if (text.includes("solar") || text.includes("energy") || text.includes("photovoltaic") || text.includes("green") || text.includes("rooftop")) {
    return {
      domainType: "solar",
      title: `${context?.businessName || "SolarTech"} Project & Installation CRM`,
      entityName: "Project Lead",
      entityPlural: "Site Projects",
      roleLabel: "System Spec / Capacity",
      stages: ["All", "Site Survey", "Design Ready", "Permit Approved", "Commissioned"],
      stageColors: {
        "Site Survey": "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
        "Design Ready": "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
        "Permit Approved": "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300",
        "Commissioned": "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
      },
      defaultRecords: [
        { id: "s001", name: "Surya Green Villas", email: "contact@suryagreen.in", role: "10 kW Hybrid Rooftop", experience: 3, stage: "Site Survey" as any, rating: 5, status: "Active", appliedDate: "2026-09-20", notes: "Requires shadow analysis for east parapet wall." },
        { id: "s002", name: "Apex Logistics Depot", email: "facilities@apexlogistics.com", role: "150 kW Commercial Net-Metered", experience: 8, stage: "Design Ready" as any, rating: 4, status: "Active", appliedDate: "2026-09-18", notes: "Single line diagram generated; awaiting grid tie approval." },
        { id: "s003", name: "Kaveri Cold Storage", email: "admin@kavericold.org", role: "50 kW Off-Grid LiFePO4", experience: 5, stage: "Permit Approved" as any, rating: 5, status: "Active", appliedDate: "2026-09-15", notes: "DISCOM NOC received. Ready for module dispatch." },
        { id: "s004", name: "Metro Tech Park", email: "green@metrotech.com", role: "300 kW Solar Carport", experience: 12, stage: "Commissioned" as any, rating: 5, status: "Hired", appliedDate: "2026-09-10", notes: "Fully synchronized with grid. Generating 1,200 kWh/day." }
      ],
      attendanceTitle: "Field Technician & Rooftop Auditor Log"
    };
  }

  if (text.includes("health") || text.includes("hospital") || text.includes("clinic") || text.includes("pharma") || text.includes("lab") || text.includes("diagnostic") || text.includes("blood") || text.includes("patient") || text.includes("trial") || text.includes("medicine")) {
    return {
      domainType: "health",
      title: `${context?.businessName || "HealthPulse"} Diagnostic & Patient CRM`,
      entityName: "Patient Case",
      entityPlural: "Patients",
      roleLabel: "Diagnostic Protocol",
      stages: ["All", "Intake", "Sample Received", "Analysis", "Completed"],
      stageColors: {
        "Intake": "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
        "Sample Received": "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
        "Analysis": "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300",
        "Completed": "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
      },
      defaultRecords: [
        { id: "h001", name: "Ramesh Verma", email: "rverma@gmail.com", role: "Comprehensive Metabolic & Lipid Panel", experience: 48, stage: "Intake" as any, rating: 5, status: "Active", appliedDate: "2026-09-22", notes: "Fasting blood sample scheduled at 08:30 AM." },
        { id: "h002", name: "Sunita Mehra", email: "sunita.m@outlook.com", role: "Thyroid & Hormone Profile", experience: 34, stage: "Sample Received" as any, rating: 4, status: "Active", appliedDate: "2026-09-21", notes: "Serum vial barcoded #LAB-9042; in centrifuge batch." },
        { id: "h003", name: "Vikram Malhotra", email: "vmalhotra@gmail.com", role: "HbA1c & Renal Function Assay", experience: 52, stage: "Analysis" as any, rating: 5, status: "Active", appliedDate: "2026-09-20", notes: "Spectrometry run finished. Pathologist review pending." },
        { id: "h004", name: "Ananya Sen", email: "ananya.sen@corp.in", role: "Annual Executive Health Package", experience: 29, stage: "Completed" as any, rating: 5, status: "Hired", appliedDate: "2026-09-18", notes: "Digital report signed & dispatched via WhatsApp/SMS." }
      ],
      attendanceTitle: "Clinical Staff & Phlebotomist Duty Clock"
    };
  }

  if (text.includes("logistics") || text.includes("freight") || text.includes("supply") || text.includes("warehouse") || text.includes("transport") || text.includes("fleet") || text.includes("delivery")) {
    return {
      domainType: "logistics",
      title: `${context?.businessName || "LogiTrack"} Freight & Shipment CRM`,
      entityName: "Consignment",
      entityPlural: "Shipments",
      roleLabel: "Route & Cargo Spec",
      stages: ["All", "Dispatched", "In Transit", "Customs / Hub", "Delivered"],
      stageColors: {
        "Dispatched": "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
        "In Transit": "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
        "Customs / Hub": "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300",
        "Delivered": "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
      },
      defaultRecords: [
        { id: "l001", name: "Waybill #WB-4921", email: "ops@expresscargo.in", role: "Electronics (Mumbai ➔ Delhi)", experience: 2, stage: "Dispatched" as any, rating: 5, status: "Active", appliedDate: "2026-09-22", notes: "Loaded onto Fleet Unit #MH-12-8821. GPS ping normal." },
        { id: "l002", name: "Pharma Cold Route #PC-102", email: "supply@biocold.com", role: "Vaccines (Pune ➔ Goa)", experience: 1, stage: "In Transit" as any, rating: 5, status: "Active", appliedDate: "2026-09-21", notes: "Reefer unit locked at 4.2°C temperature." },
        { id: "l003", name: "Freight Box #ICD-770", email: "customs@portlog.com", role: "Auto Parts (Nhava Sheva ➔ Pune)", experience: 4, stage: "Customs / Hub" as any, rating: 4, status: "Active", appliedDate: "2026-09-19", notes: "Clearance assessment cleared; gate pass issued." },
        { id: "l004", name: "Retail Goods #BLR-332", email: "dispatch@quickhaul.in", role: "FMCG Inventory (Bangalore Hub)", experience: 1, stage: "Delivered" as any, rating: 5, status: "Hired", appliedDate: "2026-09-17", notes: "Proof of delivery signed by warehouse manager." }
      ],
      attendanceTitle: "Driver & Warehouse Shift Clock"
    };
  }

  // Default: TalentCraft / HR Consultancy
  return {
    domainType: "hr",
    title: `${context?.businessName || "TalentCraft"} Workable HR CRM`,
    entityName: "Candidate",
    entityPlural: "Candidates",
    roleLabel: "Role Applied",
    stages: ["All", "Screening", "Interview", "Offer", "Rejected"],
    stageColors: {
      Screening: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
      Interview: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
      Offer: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
      Rejected: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300",
    },
    defaultRecords: HR_CRM_CANDIDATES,
    attendanceTitle: "Consultant Attendance Punch Clock"
  };
}

const STATUS_COLORS: Record<string, string> = {
  Active: "text-emerald-600 dark:text-emerald-400",
  "On Hold": "text-amber-600 dark:text-amber-400",
  Hired: "text-primary",
  Withdrawn: "text-muted-foreground",
};

/* ───────────── Main CRM Page Component ───────────── */

function CRMPage() {
  useStageGate("crm");
  const [workspaceContext, setWorkspaceContext] = useState<{
    businessName?: string;
    industry?: string;
    problemStatement?: string;
  } | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem("bizzmitra.workspaceContext");
      if (raw) {
        setWorkspaceContext(JSON.parse(raw));
      }
    } catch (e) {
      console.warn("Failed to load workspaceContext:", e);
    }
  }, []);

  const domainConfig = useMemo(() => getDomainConfig(workspaceContext), [workspaceContext]);

  const [candidates, setCandidates] = useState<CRMCandidate[]>(() => domainConfig.defaultRecords);

  // Sync default records when domain changes
  useEffect(() => {
    setCandidates(domainConfig.defaultRecords);
    setStageFilter("All");
  }, [domainConfig]);

  const [searchQuery, setSearchQuery] = useState("");
  const [stageFilter, setStageFilter] = useState<string>("All");
  const [statusFilter, setStatusFilter] = useState<string>("All");
  const [expRange, setExpRange] = useState<[number, number]>([0, 50]);
  const [showFilters, setShowFilters] = useState(false);
  const [showAddModal, setShowAddModal] = useState(false);
  const [isStudioOpen, setIsStudioOpen] = useState(false);
  const [studioSettings, setStudioSettings] = useState<StudioSettings>(() => loadStudioSettings());

  useEffect(() => {
    const handler = (e: Event) => {
      const custom = e as CustomEvent<StudioSettings>;
      if (custom.detail) {
        setStudioSettings(custom.detail);
      }
    };
    window.addEventListener("bizzmitra:studio-updated", handler);
    return () => window.removeEventListener("bizzmitra:studio-updated", handler);
  }, []);

  // Attendance state
  const [attendanceLog, setAttendanceLog] = useState<AttendanceEntry[]>([...HR_ATTENDANCE_LOG]);
  const [isPunchedIn, setIsPunchedIn] = useState(false);
  const [punchInTime, setPunchInTime] = useState<Date | null>(null);
  const [elapsed, setElapsed] = useState(0);

  // Timer for punch clock
  useEffect(() => {
    if (!isPunchedIn || !punchInTime) return;
    const id = setInterval(() => {
      setElapsed(Math.floor((Date.now() - punchInTime.getTime()) / 1000));
    }, 1000);
    return () => clearInterval(id);
  }, [isPunchedIn, punchInTime]);

  // Interactive record actions
  const handleUpdateStage = useCallback((id: string, newStage: string) => {
    setCandidates((prev) =>
      prev.map((c) => (c.id === id ? { ...c, stage: newStage as any } : c))
    );
  }, []);

  const handleUpdateRating = useCallback((id: string, newRating: number) => {
    setCandidates((prev) =>
      prev.map((c) => (c.id === id ? { ...c, rating: newRating } : c))
    );
  }, []);

  const handleDeleteRecord = useCallback((id: string) => {
    setCandidates((prev) => prev.filter((c) => c.id !== id));
  }, []);

  // Advance to next stage helper
  const handleAdvanceStage = useCallback((id: string, currentStage: string) => {
    const stageList = domainConfig.stages.filter((s) => s !== "All");
    const currentIndex = stageList.indexOf(currentStage);
    const nextIndex = (currentIndex + 1) % (stageList.length || 1);
    const nextStage = stageList[nextIndex];
    if (nextStage) {
      handleUpdateStage(id, nextStage);
    }
  }, [domainConfig.stages, handleUpdateStage]);

  // Filtered candidates
  const filtered = useMemo(() => {
    return candidates.filter((c) => {
      if (stageFilter !== "All" && c.stage !== stageFilter) return false;
      if (statusFilter !== "All" && c.status !== statusFilter) return false;
      if (c.experience < expRange[0] || c.experience > expRange[1]) return false;
      if (searchQuery) {
        const q = searchQuery.toLowerCase();
        return (
          c.name.toLowerCase().includes(q) ||
          c.role.toLowerCase().includes(q) ||
          c.email.toLowerCase().includes(q)
        );
      }
      return true;
    });
  }, [candidates, stageFilter, statusFilter, expRange, searchQuery]);

  // Stage counts
  const stageCounts = useMemo(() => {
    const counts: Record<string, number> = { All: candidates.length };
    for (const c of candidates) {
      counts[c.stage] = (counts[c.stage] || 0) + 1;
    }
    return counts;
  }, [candidates]);

  // Dynamic Theme and Density styles
  const activeAccent = useMemo(() => {
    return THEME_ACCENTS.find((a) => a.id === studioSettings.accent) || THEME_ACCENTS[0]!;
  }, [studioSettings.accent]);

  const cellDensityClass = useMemo(() => {
    switch (studioSettings.density) {
      case "compact":
        return "px-3 py-1.5 text-xs";
      case "spacious":
        return "px-5 py-3.5 text-sm";
      default:
        return "px-4 py-2.5 text-xs";
    }
  }, [studioSettings.density]);

  const colSpanCount = useMemo(() => {
    let count = 2; // Entity + Actions
    if (studioSettings.visibleStandardColumns.role) count++;
    if (studioSettings.visibleStandardColumns.experience) count++;
    if (studioSettings.visibleStandardColumns.stage) count++;
    if (studioSettings.visibleStandardColumns.rating) count++;
    if (studioSettings.visibleStandardColumns.status) count++;
    if (studioSettings.visibleStandardColumns.applied) count++;
    if (studioSettings.visibleStandardColumns.notes) count++;
    count += studioSettings.customFields.length;
    return count;
  }, [studioSettings.visibleStandardColumns, studioSettings.customFields]);

  // CSV Export with Dynamic Custom Fields
  const exportCSV = useCallback(() => {
    const baseHeaders = [`${domainConfig.entityName} Name`, "Contact / Email"];
    if (studioSettings.visibleStandardColumns.role) baseHeaders.push(domainConfig.roleLabel);
    if (studioSettings.visibleStandardColumns.experience) baseHeaders.push("Experience / Age");
    if (studioSettings.visibleStandardColumns.stage) baseHeaders.push("Stage");
    if (studioSettings.visibleStandardColumns.rating) baseHeaders.push("Rating");
    if (studioSettings.visibleStandardColumns.status) baseHeaders.push("Status");
    if (studioSettings.visibleStandardColumns.applied) baseHeaders.push("Entry Date");
    if (studioSettings.visibleStandardColumns.notes) baseHeaders.push("Notes");

    const customHeaders = studioSettings.customFields.map((f) => f.label);
    const headers = [...baseHeaders, ...customHeaders];

    const rows = filtered.map((c) => {
      const row: string[] = [c.name, c.email];
      if (studioSettings.visibleStandardColumns.role) row.push(c.role);
      if (studioSettings.visibleStandardColumns.experience) row.push(c.experience.toString());
      if (studioSettings.visibleStandardColumns.stage) row.push(c.stage);
      if (studioSettings.visibleStandardColumns.rating) row.push(c.rating.toString());
      if (studioSettings.visibleStandardColumns.status) row.push(c.status);
      if (studioSettings.visibleStandardColumns.applied) row.push(c.appliedDate);
      if (studioSettings.visibleStandardColumns.notes) row.push(`"${c.notes.replace(/"/g, '""')}"`);

      for (const field of studioSettings.customFields) {
        const val = c.customValues?.[field.key] ?? field.defaultValue ?? "";
        row.push(`"${String(val).replace(/"/g, '""')}"`);
      }
      return row;
    });

    const csv = [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
    const filename = `bizzmitra_${domainConfig.domainType}_crm_${studioSettings.version}_${new Date().toISOString().slice(0, 10)}.csv`;
    void saveAndShareFile(filename, csv, "text/csv;charset=utf-8;");
  }, [filtered, studioSettings, domainConfig]);

  // Add record handler
  const addCandidate = useCallback((candidate: Omit<CRMCandidate, "id">) => {
    setCandidates((prev) => [
      { ...candidate, id: `rec_${(prev.length + 1).toString().padStart(3, "0")}` },
      ...prev,
    ]);
    setShowAddModal(false);
  }, []);

  // Punch handlers
  const handlePunchIn = useCallback(() => {
    setIsPunchedIn(true);
    setPunchInTime(new Date());
    setElapsed(0);
  }, []);

  const handlePunchOut = useCallback(() => {
    if (!punchInTime) return;
    const now = new Date();
    const diffMs = now.getTime() - punchInTime.getTime();
    const hours = Math.floor(diffMs / 3600000);
    const mins = Math.floor((diffMs % 3600000) / 60000);
    const newEntry: AttendanceEntry = {
      id: `a${(attendanceLog.length + 1).toString().padStart(3, "0")}`,
      date: now.toISOString().slice(0, 10),
      punchIn: punchInTime.toTimeString().slice(0, 5),
      punchOut: now.toTimeString().slice(0, 5),
      hoursWorked: `${hours}h ${mins.toString().padStart(2, "0")}m`,
      consultant: "You",
    };
    setAttendanceLog((prev) => [newEntry, ...prev]);
    setIsPunchedIn(false);
    setPunchInTime(null);
    setElapsed(0);
  }, [punchInTime, attendanceLog.length]);

  const formatElapsed = (secs: number) => {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = secs % 60;
    return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  };

  return (
    <AppShell>
      <ArtifactHeader id="crm" kicker="USP #1" title={domainConfig.title} />

      <GenerationSequence
        steps={["Loading candidate pipeline…", "Hydrating filter indices…", "Connecting attendance module…", "CRM ready"]}
        run={() => generateArtifact("solution")}
      >
        <Stagger className="space-y-6">
          {/* ═══ Pipeline Stats Bar ═══ */}
          <StaggerItem className="grid gap-3 sm:grid-cols-4">
            {(
              [
                [`Total ${domainConfig.entityPlural}`, candidates.length, Users],
                ["In Pipeline", candidates.filter((c) => (c.stage as string) !== "Rejected" && (c.stage as string) !== "Completed" && (c.stage as string) !== "Delivered" && (c.stage as string) !== "Commissioned").length, Filter],
                ["Top Rated / Closed", candidates.filter((c) => (c.stage as string) === "Offer" || (c.stage as string) === "Completed" || (c.stage as string) === "Delivered" || (c.stage as string) === "Commissioned" || c.rating === 5).length, Check],
                ["Avg. Rating", (candidates.reduce((a, c) => a + c.rating, 0) / (candidates.length || 1)).toFixed(1), Star],
              ] as [string, number | string, React.ComponentType<{ className?: string }>][]
            ).map(([label, value, Icon]) => (
              <div key={label} className="neu-inset px-4 py-3 flex items-center gap-3">
                <span className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary">
                  <Icon className="size-4" />
                </span>
                <div>
                  <p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">{label}</p>
                  <p className="font-display text-xl font-extrabold">{value}</p>
                </div>
              </div>
            ))}
          </StaggerItem>

          {/* ═══ Stage Tabs + Search + Filters + Actions ═══ */}
          <StaggerItem className="neu p-4">
            {/* Stage tabs (horizontally scrollable chips on mobile) */}
            <div className="flex items-center gap-1.5 mb-4 overflow-x-auto pb-1.5 scrollbar-none sm:flex-wrap">
              {domainConfig.stages.map((s) => (
                <button
                  key={s}
                  onClick={() => setStageFilter(s)}
                  className={cn(
                    "relative shrink-0 rounded-full px-3 py-1.5 text-xs font-semibold transition-colors cursor-pointer",
                    stageFilter === s
                      ? "text-primary-foreground"
                      : "text-muted-foreground hover:text-foreground hover:bg-accent",
                  )}
                >
                  {stageFilter === s && (
                    <motion.span
                      layoutId="stage-pill"
                      className={cn("absolute inset-0 rounded-full shadow-sm", activeAccent.primaryClass)}
                      transition={{ type: "spring", stiffness: 420, damping: 34 }}
                    />
                  )}
                  <span className="relative flex items-center gap-1.5">
                    {s}
                    <span
                      className={cn(
                        "rounded-full px-1.5 py-0.5 text-[10px] font-bold",
                        stageFilter === s
                          ? "bg-primary-foreground/20 text-primary-foreground"
                          : "bg-muted text-muted-foreground",
                      )}
                    >
                      {stageCounts[s] || 0}
                    </span>
                  </span>
                </button>
              ))}
            </div>

            {/* Search + Actions */}
            <div className="flex flex-wrap items-center gap-2">
              <div className="relative flex-1 min-w-[200px]">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground pointer-events-none" />
                <input
                  type="text"
                  placeholder={`Search by name, ${domainConfig.roleLabel.toLowerCase()}, or email…`}
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full neu-inset rounded-lg py-2.5 pl-9 pr-3 text-sm outline-none placeholder:text-muted-foreground/60 focus:ring-2 focus:ring-primary/30"
                />
              </div>

              <button
                onClick={() => setShowFilters(!showFilters)}
                className={cn(
                  "neu-sm neu-press flex items-center gap-1.5 px-3 py-2.5 text-xs font-medium cursor-pointer",
                  showFilters && "ring-2 ring-primary/30",
                )}
              >
                <Filter className="size-3.5" />
                Filters
                <ChevronDown className={cn("size-3 transition-transform", showFilters && "rotate-180")} />
              </button>

              <button
                onClick={() => setShowAddModal(true)}
                className="neu-press flex items-center gap-1.5 rounded-xl bg-primary px-3.5 py-2.5 text-xs font-semibold text-primary-foreground cursor-pointer shadow-sm hover:brightness-105"
              >
                <Plus className="size-3.5" />
                Add {domainConfig.entityName}
              </button>

              <button
                onClick={exportCSV}
                className="neu-sm neu-press flex items-center gap-1.5 px-3 py-2.5 text-xs font-medium cursor-pointer"
              >
                <Download className="size-3.5" />
                Export CSV
              </button>

              <button
                onClick={() => setIsStudioOpen(true)}
                className={cn(
                  "neu-press flex items-center gap-1.5 rounded-xl px-3.5 py-2.5 text-xs font-semibold shadow-sm hover:brightness-105 cursor-pointer",
                  activeAccent.primaryClass,
                )}
              >
                <Sliders className="size-3.5" />
                Solution Studio
                <span className="rounded-full bg-white/25 px-1.5 py-0.2 text-[9px] font-mono">
                  {studioSettings.version}
                </span>
                <span className="size-2 rounded-full border border-white/60 bg-white" />
              </button>
            </div>

            {/* Expandable Filters */}
            <AnimatePresence>
              {showFilters && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.25 }}
                  className="overflow-hidden"
                >
                  <div className="mt-3 flex flex-wrap items-center gap-4 rounded-lg bg-accent/40 p-3">
                    <div>
                      <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                        Status
                      </label>
                      <select
                        value={statusFilter}
                        onChange={(e) => setStatusFilter(e.target.value)}
                        className="mt-1 block w-full min-w-[120px] neu-inset rounded-lg px-2 py-1.5 text-xs outline-none"
                      >
                        <option>All</option>
                        <option>Active</option>
                        <option>On Hold</option>
                        <option>Hired</option>
                        <option>Withdrawn</option>
                      </select>
                    </div>
                    <div>
                      <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                        Metric / Exp (min)
                      </label>
                      <input
                        type="number"
                        min={0}
                        max={expRange[1]}
                        value={expRange[0]}
                        onChange={(e) => setExpRange([Number(e.target.value), expRange[1]])}
                        className="mt-1 block w-20 neu-inset rounded-lg px-2 py-1.5 text-xs outline-none"
                      />
                    </div>
                    <div>
                      <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                        Metric / Exp (max)
                      </label>
                      <input
                        type="number"
                        min={expRange[0]}
                        max={100}
                        value={expRange[1]}
                        onChange={(e) => setExpRange([expRange[0], Number(e.target.value)])}
                        className="mt-1 block w-20 neu-inset rounded-lg px-2 py-1.5 text-xs outline-none"
                      />
                    </div>
                    <button
                      onClick={() => {
                        setStatusFilter("All");
                        setExpRange([0, 50]);
                        setSearchQuery("");
                        setStageFilter("All");
                      }}
                      className="mt-4 text-xs text-primary font-semibold hover:underline cursor-pointer"
                    >
                      Reset all
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </StaggerItem>

          {/* ═══ Candidate Data Table (Desktop/Tablet) & Cards (Phone) ═══ */}
          <StaggerItem className="neu overflow-hidden">
            {/* Phone View: Card List (< 640px) */}
            <div className="block sm:hidden divide-y divide-border/60">
              {filtered.length === 0 ? (
                <div className="p-8 text-center text-xs text-muted-foreground">
                  No {domainConfig.entityPlural.toLowerCase()} match your current filters.
                </div>
              ) : (
                filtered.map((c) => (
                  <div key={`card-${c.id}`} className="p-3.5 space-y-2 bg-card/40">
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <h4 className="text-sm font-bold text-foreground">{c.name}</h4>
                        <p className="text-[11px] text-muted-foreground">{c.email}</p>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <button
                          type="button"
                          onClick={() => handleAdvanceStage(c.id, c.stage)}
                          title="Click to advance stage"
                          className={cn(
                            "inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-bold shrink-0 cursor-pointer shadow-xs active:scale-95",
                            domainConfig.stageColors[c.stage] || "bg-muted text-muted-foreground",
                          )}
                        >
                          {c.stage}
                          <RefreshCw className="size-2 opacity-60" />
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDeleteRecord(c.id)}
                          title="Delete entry"
                          className="rounded p-1 text-muted-foreground hover:bg-destructive/10 hover:text-destructive transition-colors cursor-pointer"
                        >
                          <Trash2 className="size-3" />
                        </button>
                      </div>
                    </div>

                    <div className="flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground">
                      <span className="font-semibold text-foreground">{c.role}</span>
                      <span>•</span>
                      <span>{c.experience} metric</span>
                      <span>•</span>
                      <span className={cn("font-medium", STATUS_COLORS[c.status] || "text-foreground")}>
                        {c.status}
                      </span>
                      <span>•</span>
                      <div className="flex items-center gap-0.5">
                        {[1, 2, 3, 4, 5].map((i) => (
                          <button
                            key={i}
                            type="button"
                            onClick={() => handleUpdateRating(c.id, i)}
                            className="p-0.5 cursor-pointer"
                          >
                            <Star
                              className={cn(
                                "size-2.5",
                                i <= c.rating ? "fill-amber-400 text-amber-400" : "text-border",
                              )}
                            />
                          </button>
                        ))}
                      </div>
                    </div>

                    {c.notes && (
                      <p className="text-[11px] text-muted-foreground/90 line-clamp-2 bg-surface/50 p-2 rounded-lg">
                        {c.notes}
                      </p>
                    )}

                    {/* Custom fields on mobile card */}
                    {studioSettings.customFields.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 pt-1">
                        {studioSettings.customFields.map((field) => {
                          const rawVal = c.customValues?.[field.key] ?? field.defaultValue ?? "—";
                          const val = String(rawVal);
                          return (
                            <span
                              key={field.id}
                              className={cn(
                                "inline-flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-medium border",
                                activeAccent.badgeClass,
                                activeAccent.borderClass,
                              )}
                            >
                              <Tag className="size-2 opacity-60" />
                              <span className="opacity-75">{field.label}:</span>
                              <span className="font-semibold">{val}</span>
                            </span>
                          );
                        })}
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>

            {/* Tablet & Desktop View: Table (>= 640px) */}
            <div className="hidden sm:block overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead>
                  <tr className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground border-b border-border bg-surface/60">
                    <th className={cn(cellDensityClass, "font-semibold")}>{domainConfig.entityName}</th>
                    {studioSettings.visibleStandardColumns.role && (
                      <th className={cn(cellDensityClass, "font-semibold")}>{domainConfig.roleLabel}</th>
                    )}
                    {studioSettings.visibleStandardColumns.experience && (
                      <th className={cn(cellDensityClass, "font-semibold text-center")}>Metric</th>
                    )}
                    {studioSettings.visibleStandardColumns.stage && (
                      <th className={cn(cellDensityClass, "font-semibold")}>Stage (Click to Advance)</th>
                    )}
                    {studioSettings.visibleStandardColumns.rating && (
                      <th className={cn(cellDensityClass, "font-semibold text-center")}>Rating</th>
                    )}
                    {studioSettings.visibleStandardColumns.status && (
                      <th className={cn(cellDensityClass, "font-semibold")}>Status</th>
                    )}
                    {studioSettings.visibleStandardColumns.applied && (
                      <th className={cn(cellDensityClass, "font-semibold")}>Date</th>
                    )}
                    {studioSettings.visibleStandardColumns.notes && (
                      <th className={cn(cellDensityClass, "font-semibold")}>Notes</th>
                    )}
                    {/* Dynamic Custom Columns */}
                    {studioSettings.customFields.map((field) => (
                      <th
                        key={field.id}
                        className={cn(cellDensityClass, "font-semibold")}
                        style={{ color: activeAccent.colorHex }}
                      >
                        <span className="flex items-center gap-1">
                          <Tag className="size-2.5 opacity-70" />
                          {field.label}
                        </span>
                      </th>
                    ))}
                    <th className={cn(cellDensityClass, "font-semibold text-right")}>Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/50">
                  <AnimatePresence>
                    {filtered.length === 0 ? (
                      <tr>
                        <td
                          colSpan={colSpanCount}
                          className="py-12 text-center text-sm text-muted-foreground"
                        >
                          No {domainConfig.entityPlural.toLowerCase()} match your current filters.
                        </td>
                      </tr>
                    ) : (
                      filtered.map((c) => (
                        <motion.tr
                          key={c.id}
                          layout
                          initial={{ opacity: 0, y: 6 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -6 }}
                          transition={{ duration: 0.2 }}
                          className={cn(
                            "group align-top transition-colors hover:bg-card/70",
                            studioSettings.alternateRows && "odd:bg-card/35 even:bg-transparent",
                          )}
                        >
                          <td className={cellDensityClass}>
                            <p className="text-xs font-bold">{c.name}</p>
                            <p className="text-[10px] text-muted-foreground">{c.email}</p>
                          </td>
                          {studioSettings.visibleStandardColumns.role && (
                            <td className={cn(cellDensityClass, "text-foreground")}>{c.role}</td>
                          )}
                          {studioSettings.visibleStandardColumns.experience && (
                            <td className={cn(cellDensityClass, "text-center font-medium tabular-nums")}>
                              {c.experience}
                            </td>
                          )}
                          {studioSettings.visibleStandardColumns.stage && (
                            <td className={cellDensityClass}>
                              <button
                                type="button"
                                onClick={() => handleAdvanceStage(c.id, c.stage)}
                                title="Click to advance stage"
                                className={cn(
                                  "inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[10px] font-bold cursor-pointer transition-all hover:scale-105 active:scale-95 shadow-xs",
                                  domainConfig.stageColors[c.stage] || "bg-muted text-muted-foreground",
                                )}
                              >
                                {c.stage}
                                <RefreshCw className="size-2.5 opacity-60" />
                              </button>
                            </td>
                          )}
                          {studioSettings.visibleStandardColumns.rating && (
                            <td className={cn(cellDensityClass, "text-center")}>
                              <div className="flex items-center justify-center gap-0.5">
                                {[1, 2, 3, 4, 5].map((i) => (
                                  <button
                                    key={i}
                                    type="button"
                                    onClick={() => handleUpdateRating(c.id, i)}
                                    title={`Rate ${i} stars`}
                                    className="p-0.5 hover:scale-125 transition-transform cursor-pointer"
                                  >
                                    <Star
                                      className={cn(
                                        "size-3",
                                        i <= c.rating
                                          ? "fill-amber-400 text-amber-400"
                                          : "text-border hover:text-amber-300",
                                      )}
                                    />
                                  </button>
                                ))}
                              </div>
                            </td>
                          )}
                          {studioSettings.visibleStandardColumns.status && (
                            <td className={cellDensityClass}>
                              <span
                                className={cn(
                                  "text-xs font-medium",
                                  STATUS_COLORS[c.status] || "text-foreground",
                                )}
                              >
                                {c.status}
                              </span>
                            </td>
                          )}
                          {studioSettings.visibleStandardColumns.applied && (
                            <td className={cn(cellDensityClass, "text-muted-foreground tabular-nums")}>
                              {c.appliedDate}
                            </td>
                          )}
                          {studioSettings.visibleStandardColumns.notes && (
                            <td className={cn(cellDensityClass, "text-[10px] text-muted-foreground max-w-[180px] truncate")}>
                              {c.notes}
                            </td>
                          )}
                          {/* Dynamic Custom Attribute Cells */}
                          {studioSettings.customFields.map((field) => {
                            const rawVal = c.customValues?.[field.key] ?? field.defaultValue ?? "—";
                            const val = String(rawVal);
                            const isUrl =
                              field.type === "url" &&
                              (val.startsWith("http://") || val.startsWith("https://"));

                            return (
                              <td key={field.id} className={cellDensityClass}>
                                {isUrl ? (
                                  <a
                                    href={val}
                                    target="_blank"
                                    rel="noreferrer"
                                    className={cn(
                                      "inline-flex items-center gap-1 rounded px-2 py-0.5 text-[11px] font-medium hover:underline border",
                                      activeAccent.badgeClass,
                                      activeAccent.borderClass,
                                    )}
                                  >
                                    <ExternalLink className="size-2.5" />
                                    Link
                                  </a>
                                ) : (
                                  <span
                                    className={cn(
                                      "inline-block rounded px-2 py-0.5 text-[11px] font-medium border",
                                      activeAccent.badgeClass,
                                      activeAccent.borderClass,
                                    )}
                                  >
                                    {val}
                                  </span>
                                )}
                              </td>
                            );
                          })}
                          <td className={cn(cellDensityClass, "text-right")}>
                            <button
                              type="button"
                              onClick={() => handleDeleteRecord(c.id)}
                              title="Delete record"
                              className="rounded p-1 text-muted-foreground hover:bg-destructive/10 hover:text-destructive transition-colors cursor-pointer"
                            >
                              <Trash2 className="size-3.5" />
                            </button>
                          </td>
                        </motion.tr>
                      ))
                    )}
                  </AnimatePresence>
                </tbody>
              </table>
            </div>
            <div className="border-t border-border px-4 py-2.5 text-xs text-muted-foreground">
              Showing {filtered.length} of {candidates.length} {domainConfig.entityPlural.toLowerCase()}
            </div>
          </StaggerItem>

          {/* ═══ Attendance Punch Clock ═══ */}
          <StaggerItem className="neu p-6">
            <div className="flex items-center gap-2 text-primary font-bold text-xs uppercase tracking-wider mb-1">
              <Clock className="size-3.5" />
              <span>{domainConfig.attendanceTitle}</span>
            </div>
            <h3 className="font-display text-lg font-bold">Operational Shift Check-In / Check-Out</h3>

            <div className="mt-5 flex flex-col sm:flex-row items-start sm:items-center gap-4">
              {/* Punch button */}
              <button
                type="button"
                onClick={isPunchedIn ? handlePunchOut : handlePunchIn}
                className={cn(
                  "neu-press flex items-center gap-2.5 rounded-xl px-6 py-3.5 text-sm font-bold transition-all cursor-pointer",
                  isPunchedIn
                    ? "bg-destructive text-destructive-foreground hover:brightness-110"
                    : "bg-sage text-sage-foreground hover:brightness-110",
                )}
              >
                {isPunchedIn ? (
                  <>
                    <Timer className="size-4 animate-pulse" />
                    Punch Out
                  </>
                ) : (
                  <>
                    <Clock className="size-4" />
                    Punch In
                  </>
                )}
              </button>

              {/* Live timer display */}
              {isPunchedIn && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="neu-inset px-5 py-3 rounded-lg"
                >
                  <p className="text-[10px] uppercase tracking-wider text-muted-foreground">
                    Session elapsed
                  </p>
                  <p className="font-mono text-2xl font-bold text-primary tabular-nums">
                    {formatElapsed(elapsed)}
                  </p>
                  <p className="text-[10px] text-muted-foreground">
                    Punched in at {punchInTime?.toTimeString().slice(0, 5)}
                  </p>
                </motion.div>
              )}

              {!isPunchedIn && (
                <div className="neu-inset px-5 py-3 rounded-lg">
                  <p className="text-[10px] uppercase tracking-wider text-muted-foreground">
                    Status
                  </p>
                  <p className="text-sm font-semibold text-muted-foreground">Not clocked in</p>
                </div>
              )}
            </div>

            {/* Punch log table */}
            <div className="mt-5 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead>
                  <tr className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground border-b border-border">
                    <th className="pb-2 pr-4 font-semibold">Date</th>
                    <th className="pb-2 pr-4 font-semibold">Punch In</th>
                    <th className="pb-2 pr-4 font-semibold">Punch Out</th>
                    <th className="pb-2 pr-4 font-semibold">Hours Worked</th>
                    <th className="pb-2 font-semibold">Staff / Field Agent</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/60">
                  {attendanceLog.slice(0, 7).map((entry) => (
                    <motion.tr
                      key={entry.id}
                      layout
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="hover:bg-card/40 transition-colors"
                    >
                      <td className="py-2.5 pr-4 text-xs font-medium tabular-nums">{entry.date}</td>
                      <td className="py-2.5 pr-4 text-xs text-sage font-semibold tabular-nums">{entry.punchIn}</td>
                      <td className="py-2.5 pr-4 text-xs text-muted-foreground tabular-nums">
                        {entry.punchOut || "—"}
                      </td>
                      <td className="py-2.5 pr-4 text-xs font-bold tabular-nums">{entry.hoursWorked}</td>
                      <td className="py-2.5 text-xs text-muted-foreground">{entry.consultant}</td>
                    </motion.tr>
                  ))}
                </tbody>
              </table>
            </div>
          </StaggerItem>
        </Stagger>
      </GenerationSequence>

      {/* ═══ Add Entry Modal ═══ */}
      <AnimatePresence>
        {showAddModal && (
          <AddCandidateModal
            onClose={() => setShowAddModal(false)}
            onAdd={addCandidate}
            customFields={studioSettings.customFields}
            entityName={domainConfig.entityName}
            roleLabel={domainConfig.roleLabel}
            stages={domainConfig.stages.filter((s) => s !== "All")}
          />
        )}
      </AnimatePresence>

      {/* ═══ Solution Studio Slide-Out Drawer ═══ */}
      <SolutionStudioDrawer
        isOpen={isStudioOpen}
        onClose={() => setIsStudioOpen(false)}
        onSettingsChange={(newSettings) => setStudioSettings(newSettings)}
      />
    </AppShell>
  );
}

/* ───────────── Add Entry Modal ───────────── */

function AddCandidateModal({
  onClose,
  onAdd,
  customFields = [],
  entityName = "Candidate",
  roleLabel = "Role Applied",
  stages = ["Screening", "Interview", "Offer", "Rejected"],
}: {
  onClose: () => void;
  onAdd: (c: Omit<CRMCandidate, "id">) => void;
  customFields?: CustomField[];
  entityName?: string;
  roleLabel?: string;
  stages?: string[];
}) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [role, setRole] = useState("");
  const [experience, setExperience] = useState("");
  const [stage, setStage] = useState<string>(stages[0] || "Screening");
  const [notes, setNotes] = useState("");
  const [customValues, setCustomValues] = useState<Record<string, string>>(() => {
    const init: Record<string, string> = {};
    for (const f of customFields) {
      if (f.defaultValue) init[f.key] = f.defaultValue;
    }
    return init;
  });
  const nameRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    nameRef.current?.focus();
  }, []);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !email || !role) return;
    onAdd({
      name,
      email,
      role,
      experience: Number(experience) || 0,
      stage: stage as any,
      rating: 3,
      status: "Active",
      appliedDate: new Date().toISOString().slice(0, 10),
      notes,
      customValues,
    });
  };

  return (
    <motion.div
      className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 backdrop-blur-sm p-4"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
    >
      <motion.div
        className="neu w-full max-w-lg p-6 max-h-[90vh] overflow-y-auto"
        initial={{ scale: 0.92, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.92, opacity: 0, y: 20 }}
        transition={{ type: "spring", stiffness: 400, damping: 30 }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-5">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">
              New {entityName}
            </p>
            <h3 className="font-display text-xl font-extrabold mt-0.5">
              Pipeline Entry
            </h3>
          </div>
          <button
            onClick={onClose}
            className="grid size-8 place-items-center rounded-lg hover:bg-accent transition-colors cursor-pointer"
          >
            <X className="size-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                {entityName} Name *
              </label>
              <input
                ref={nameRef}
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder={`e.g., Primary ${entityName}`}
                required
                className="mt-1 w-full neu-inset rounded-lg px-3 py-2.5 text-sm outline-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/30"
              />
            </div>
            <div>
              <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                Contact / Email *
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="e.g., contact@domain.com"
                required
                className="mt-1 w-full neu-inset rounded-lg px-3 py-2.5 text-sm outline-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/30"
              />
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                {roleLabel} *
              </label>
              <input
                value={role}
                onChange={(e) => setRole(e.target.value)}
                placeholder={`e.g., Primary specification`}
                required
                className="mt-1 w-full neu-inset rounded-lg px-3 py-2.5 text-sm outline-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/30"
              />
            </div>
            <div>
              <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                Metric / Experience
              </label>
              <input
                type="number"
                min={0}
                max={100}
                value={experience}
                onChange={(e) => setExperience(e.target.value)}
                placeholder="e.g., 5"
                className="mt-1 w-full neu-inset rounded-lg px-3 py-2.5 text-sm outline-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/30"
              />
            </div>
          </div>

          <div>
            <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
              Pipeline Stage
            </label>
            <select
              value={stage}
              onChange={(e) => setStage(e.target.value)}
              className="mt-1 w-full neu-inset rounded-lg px-3 py-2.5 text-sm outline-none"
            >
              {stages.map((stg) => (
                <option key={stg} value={stg}>
                  {stg}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
              Notes
            </label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Any relevant operational notes…"
              rows={2}
              className="mt-1 w-full neu-inset rounded-lg px-3 py-2.5 text-sm outline-none resize-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/30"
            />
          </div>

          {/* Dynamic Custom Schema Attributes */}
          {customFields.length > 0 && (
            <div className="pt-3 border-t border-border/60 space-y-2.5">
              <p className="text-[10px] font-bold uppercase tracking-wider text-primary flex items-center gap-1">
                <Tag className="size-3" />
                Custom Schema Attributes ({customFields.length})
              </p>
              <div className="grid gap-3 sm:grid-cols-2">
                {customFields.map((field) => (
                  <div key={field.id}>
                    <label className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                      {field.label} {field.required && "*"}
                    </label>
                    <input
                      type={
                        field.type === "number"
                          ? "number"
                          : field.type === "url"
                            ? "url"
                            : field.type === "date"
                              ? "date"
                              : "text"
                      }
                      value={customValues[field.key] ?? ""}
                      onChange={(e) =>
                        setCustomValues((prev) => ({ ...prev, [field.key]: e.target.value }))
                      }
                      placeholder={field.placeholder || `Enter ${field.label.toLowerCase()}…`}
                      required={field.required}
                      className="mt-1 w-full neu-inset rounded-lg px-3 py-2 text-xs outline-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/30"
                    />
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="flex justify-end gap-2 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="neu-sm neu-press px-4 py-2.5 text-sm font-medium cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="neu-press rounded-xl bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground cursor-pointer hover:brightness-105"
            >
              Add to {entityName} Pipeline
            </button>
          </div>
        </form>
      </motion.div>
    </motion.div>
  );
}
