import { createFileRoute } from "@tanstack/react-router";
import { Sparkles, Layout, Compass } from "lucide-react";

import { AppShell } from "@/components/AppShell";
import { ArtifactHeader } from "@/components/ArtifactHeader";
import { GenerationSequence } from "@/components/GenerationSequence";
import { Mermaid } from "@/components/Mermaid";
import { Stagger, StaggerItem } from "@/components/motion/primitives";
import { GENERATION_STEPS, generateArtifact } from "@/lib/ai/generate-artifact";
import { NAV_FLOW_DIAGRAM, WIREFRAMES } from "@/lib/demo-data";
import { WireframeVisualizer } from "@/components/WireframeVisualizer";

export const Route = createFileRoute("/workspace/wireframes")({
  head: () => ({
    meta: [
      { title: "AI UX Designer & Wireframes — BizzMitra-AI" },
      { name: "description", content: "Interactive screen concepts, responsive wireframes, and navigation flows generated by the AI UX Designer." },
      { property: "og:title", content: "AI UX Designer & Wireframes — BizzMitra-AI" },
      { property: "og:description", content: "Interactive wireframes and navigation flow concepts." },
    ],
  }),
  component: WireframesPage,
});

function WireframesPage() {
  return (
    <AppShell>
      <ArtifactHeader
        id="wireframes"
        kicker="Step 06 • AI UX Designer"
        title="Interactive Wireframes & Screen Concepts"
      />

      <GenerationSequence steps={GENERATION_STEPS.ux} run={() => generateArtifact("ux")}>
        <Stagger className="space-y-8">
          {/* Main Feature: Interactive Multi-Device Wireframe Visualizer */}
          <StaggerItem>
            <WireframeVisualizer />
          </StaggerItem>

          {/* Screen Concept Inventory */}
          <StaggerItem className="neu p-6 space-y-4">
            <div className="flex items-center gap-2 border-b border-border/60 pb-3">
              <Layout className="size-4 text-primary" />
              <h3 className="font-display text-base font-bold text-foreground">
                Screen Architecture & Component Inventory
              </h3>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              {WIREFRAMES.map((w) => (
                <div key={w.id} className="neu-sm p-4 rounded-xl border border-border/70 bg-surface/50 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-mono text-primary uppercase font-bold">ID: {w.id}</span>
                    <span className="size-2 rounded-full bg-emerald-500" />
                  </div>
                  <p className="text-xs font-bold text-foreground">{w.name}</p>
                  <p className="text-[11px] text-muted-foreground leading-relaxed">{w.note}</p>
                </div>
              ))}
            </div>
          </StaggerItem>

          {/* User Journey & Navigation Flow Diagram */}
          <StaggerItem className="neu overflow-x-auto p-6 space-y-3">
            <div className="flex items-center gap-2 border-b border-border/60 pb-3">
              <Compass className="size-4 text-primary" />
              <div>
                <h3 className="font-display text-base font-bold text-foreground">
                  User Journey & Screen Navigation Flow
                </h3>
                <p className="text-xs text-muted-foreground">
                  End-to-end navigational routing between screens, authentication gates, and modals.
                </p>
              </div>
            </div>
            <div className="mt-4">
              <Mermaid chart={NAV_FLOW_DIAGRAM} />
            </div>
          </StaggerItem>
        </Stagger>
      </GenerationSequence>
    </AppShell>
  );
}
