import { createFileRoute, Link } from "@tanstack/react-router";
import {
  AlertCircle,
  ArrowRight,
  BarChart3,
  Calendar,
  CheckCircle2,
  Clock,
  Coins,
  Copy,
  Download,
  Flame,
  HelpCircle,
  IndianRupee,
  Layers,
  Sparkles,
  TrendingUp,
  Users,
} from "lucide-react";
import { motion } from "motion/react";
import { useEffect, useMemo, useState } from "react";
import {
  Area,
  AreaChart,
  CartesianGrid,
  Legend,
  PolarAngleAxis,
  PolarGrid,
  Radar,
  RadarChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { toast } from "sonner";

import { AppShell } from "@/components/AppShell";
import { ArtifactHeader } from "@/components/ArtifactHeader";
import { CountUp, Reveal } from "@/components/motion/primitives";
import {
  computeHrRoi,
  DomainRoiBlueprint,
  getRoiBlueprint,
  HrRoiInputs,
} from "@/lib/roi-data";

export const Route = createFileRoute("/workspace/insights")({
  head: () => ({
    meta: [
      { title: "Dynamic ROI & Transformation Dashboard — BizzMitra-AI" },
      {
        name: "description",
        content: "Interactive financial return calculator, 36-month value projection curve, and digital readiness radar.",
      },
      { property: "og:title", content: "Dynamic ROI & Transformation Dashboard — BizzMitra-AI" },
      { property: "og:description", content: "Real-time financial payback modeling and enterprise impact analytics." },
    ],
  }),
  component: InsightsPage,
});

type RoiTab = "calculator" | "projection" | "readiness" | "all";

export function InsightsPage() {
  const [activeTab, setActiveTab] = useState<RoiTab>("all");
  const [workspaceContext, setWorkspaceContext] = useState<{
    id?: string;
    name?: string;
    businessName?: string;
    industry?: string;
    problemStatement?: string;
    description?: string;
  } | null>(null);

  useEffect(() => {
    try {
      const raw = localStorage.getItem("bizzmitra.workspaceContext");
      if (raw) {
        setWorkspaceContext(JSON.parse(raw));
      }
    } catch {}
  }, []);

  const blueprint: DomainRoiBlueprint = useMemo(
    () => getRoiBlueprint(workspaceContext),
    [workspaceContext]
  );

  const [inputs, setInputs] = useState<HrRoiInputs>(blueprint.defaultInputs);

  // Sync inputs if domain switches
  useEffect(() => {
    setInputs(blueprint.defaultInputs);
  }, [blueprint.domainId]);

  const roi = useMemo(
    () => computeHrRoi(inputs, blueprint.platformCostInr),
    [inputs, blueprint.platformCostInr]
  );

  const formatInr = (val: number) => {
    if (val >= 10000000) return `₹${(val / 10000000).toFixed(2)} Cr`;
    if (val >= 100000) return `₹${(val / 100000).toFixed(2)} L`;
    return `₹${val.toLocaleString("en-IN")}`;
  };

  const copyExecutiveSummary = () => {
    const summary = `EXECUTIVE ROI SUMMARY — ${blueprint.scenarioName}
==================================================
• Net Annual Savings: ${formatInr(roi.netAnnualSavingsInr)}
• Total Annual Business Value: ${formatInr(roi.totalAnnualBenefitInr)}
• Payback Period: ${roi.paybackPeriodMonths} Months
• 3-Year ROI Multiple: ${roi.threeYearRoiMultiplePct}%
• Specialist Hours Reclaimed: ${roi.annualHoursSaved.toLocaleString()} hrs/year (${roi.fullTimeEquivalentsReclaimed} FTE equivalent)
• Cycle Acceleration: ${roi.turnaroundDropPct}%
• Annual Platform Investment: ${formatInr(roi.annualPlatformInvestmentInr)}

Generated by BizzMitra-AI Transformation Cockpit`;

    navigator.clipboard.writeText(summary);
    toast.success("Executive ROI summary copied to clipboard!");
  };

  const downloadRoiReport = () => {
    const report = `# ${blueprint.scenarioName}\n\nExecutive Subtitle: ${blueprint.executiveSubtitle}\n\n## Key Financial Metrics:\n- Net Annual Savings: ${formatInr(roi.netAnnualSavingsInr)}\n- Gross Annual Value: ${formatInr(roi.totalAnnualBenefitInr)}\n- Payback Velocity: ${roi.paybackPeriodMonths} Months\n- 3-Year ROI Multiple: ${roi.threeYearRoiMultiplePct}%\n- Labor Hours Saved: ${roi.annualHoursSaved} hrs/year (${roi.fullTimeEquivalentsReclaimed} FTE)\n- Platform Investment: ${formatInr(roi.annualPlatformInvestmentInr)}\n\n## Operational Benchmarks:\n${blueprint.benchmarks.map((b) => `- ${b.metric}: Before ${b.before} -> After ${b.after} (${b.change})`).join("\n")}\n\n## Readiness Scores:\n${blueprint.readinessRadar.map((r) => `- ${r.dimension}: ${r.score}% (Industry Benchmark: ${r.benchmark}%)`).join("\n")}`;

    const blob = new Blob([report], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${blueprint.domainId}_roi_readiness_report.md`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success("Financial ROI report downloaded!");
  };

  return (
    <AppShell>
      <ArtifactHeader
        id="dashboard"
        kicker="Transformation Cockpit · Step 10"
        title="Financial ROI & Readiness Engine"
      />

      {/* Blueprint Context Banner */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-2 rounded-xl border border-primary/20 bg-primary/5 px-4 py-2.5 text-xs">
        <div className="flex items-center gap-2">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          <span className="text-muted-foreground">Financial Engineering Context:</span>
          <span className="font-bold text-foreground">
            {workspaceContext?.businessName || workspaceContext?.name || blueprint.scenarioName}
          </span>
          <span className="rounded-full bg-primary/10 px-2 py-0.5 font-medium text-primary">
            {blueprint.domainTitle}
          </span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/workspace/roadmap" className="font-medium text-muted-foreground hover:text-primary transition-colors">
            Roadmap →
          </Link>
          <Link to="/workspace/map" className="font-medium text-primary hover:underline">
            Artifact Map →
          </Link>
        </div>
      </div>

      <div className="space-y-8 pb-16">
        {/* Top Hero Banner */}
        <Reveal className="neu p-6 md:p-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <div className="max-w-2xl space-y-2">
              <div className="flex items-center gap-2">
                <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
                  <TrendingUp className="size-3.5" />
                  Live Dynamic ROI Model · Validated Formula
                </span>
                <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
                  Payback: {roi.paybackPeriodMonths} mo
                </span>
              </div>
              <h1 className="font-display text-2xl font-bold tracking-tight sm:text-3xl">
                Transformation Economics: {blueprint.scenarioName}
              </h1>
              <p className="text-sm leading-relaxed text-muted-foreground">
                {blueprint.executiveSubtitle}
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <button
                type="button"
                onClick={copyExecutiveSummary}
                className="neu-sm neu-press flex items-center gap-2 px-3.5 py-2 text-xs font-semibold hover:text-primary"
              >
                <Copy className="size-3.5" />
                Copy Executive Case
              </button>
              <button
                type="button"
                onClick={downloadRoiReport}
                className="neu-sm neu-press flex items-center gap-2 px-3.5 py-2 text-xs font-semibold hover:text-primary"
              >
                <Download className="size-3.5" />
                Download Report
              </button>
              <Link
                to="/workspace/map"
                className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground shadow-sm transition hover:opacity-90"
              >
                Inspect Artifact Map
                <ArrowRight className="size-3.5" />
              </Link>
            </div>
          </div>

          {/* Key Executive KPI Cards - standard grid without viewport unmount bugs */}
          <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>Net Annual Value</span>
                <IndianRupee className="size-4 text-emerald-500" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold text-emerald-600 dark:text-emerald-400">
                {formatInr(roi.netAnnualSavingsInr)}
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Gross: {formatInr(roi.totalAnnualBenefitInr)}
              </p>
            </div>

            <div className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>Payback Velocity</span>
                <Clock className="size-4 text-primary" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold">
                {roi.paybackPeriodMonths} <span className="text-base font-normal text-muted-foreground">Months</span>
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Break-even within Q1
              </p>
            </div>

            <div className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>3-Year Cumulative ROI</span>
                <Flame className="size-4 text-amber-500" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold text-amber-600 dark:text-amber-400">
                {roi.threeYearRoiMultiplePct}%
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Net gain on platform cost
              </p>
            </div>

            <div className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>Hours Reclaimed / Yr</span>
                <Users className="size-4 text-blue-500" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold">
                <CountUp to={roi.annualHoursSaved} /> <span className="text-base font-normal text-muted-foreground">hrs</span>
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Equiv. to {roi.fullTimeEquivalentsReclaimed} FTE specialists
              </p>
            </div>
          </div>
        </Reveal>

        {/* View Selection Tabs */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border/40 pb-3">
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              onClick={() => setActiveTab("all")}
              className={`rounded-lg px-3.5 py-1.5 text-xs font-semibold transition ${
                activeTab === "all"
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "neu hover:bg-accent/40 text-foreground"
              }`}
            >
              Full Executive Cockpit
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("calculator")}
              className={`rounded-lg px-3.5 py-1.5 text-xs font-semibold transition ${
                activeTab === "calculator"
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "neu hover:bg-accent/40 text-foreground"
              }`}
            >
              ROI Input Variables
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("projection")}
              className={`rounded-lg px-3.5 py-1.5 text-xs font-semibold transition ${
                activeTab === "projection"
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "neu hover:bg-accent/40 text-foreground"
              }`}
            >
              36-Month Trajectory & Sensitivity
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("readiness")}
              className={`rounded-lg px-3.5 py-1.5 text-xs font-semibold transition ${
                activeTab === "readiness"
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "neu hover:bg-accent/40 text-foreground"
              }`}
            >
              Readiness Radar & Benchmarks
            </button>
          </div>
          <span className="text-xs text-muted-foreground font-mono">
            Interactive Calculator Active
          </span>
        </div>

        {/* Main Grid: Calculator & Trajectory */}
        {(activeTab === "all" || activeTab === "calculator" || activeTab === "projection") && (
          <motion.div
            key={`section-main-${activeTab}`}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.2 }}
            className={`grid gap-8 ${
              activeTab === "calculator"
                ? "grid-cols-1 max-w-2xl mx-auto"
                : activeTab === "projection"
                  ? "grid-cols-1"
                  : "lg:grid-cols-12"
            }`}
          >
            {/* Left Col: Interactive Sliders */}
            {(activeTab === "all" || activeTab === "calculator") && (
              <div className={`space-y-6 ${activeTab === "all" ? "lg:col-span-5" : "w-full"}`}>
                <div className="neu p-6 space-y-6">
                  <div className="flex items-center justify-between border-b border-border/40 pb-4">
                    <div>
                      <h3 className="font-display text-base font-bold">Dynamic ROI Input Variables</h3>
                      <p className="text-xs text-muted-foreground">
                        Adjust parameters to recalculate savings instantly in real time.
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => setInputs(blueprint.defaultInputs)}
                      className="text-[11px] font-semibold text-primary hover:underline"
                    >
                      Reset Defaults
                    </button>
                  </div>

                  <div className="space-y-5">
                    {blueprint.sliders.map((s) => {
                      const val = inputs[s.key] ?? 0;
                      return (
                        <div key={s.key} className="space-y-1.5">
                          <div className="flex justify-between text-xs">
                            <span className="font-bold text-foreground">{s.label}</span>
                            <span className="font-mono font-bold text-primary">
                              {val.toLocaleString("en-IN")} {s.unit}
                            </span>
                          </div>
                          <input
                            type="range"
                            min={s.min}
                            max={s.max}
                            step={s.step}
                            value={val}
                            onChange={(e) =>
                              setInputs((prev) => ({ ...prev, [s.key]: Number(e.target.value) }))
                            }
                            className="w-full accent-primary cursor-pointer"
                          />
                          <p className="text-[10px] text-muted-foreground">{s.desc}</p>
                        </div>
                      );
                    })}
                  </div>

                  {/* Breakdown Breakdown */}
                  <div className="space-y-2 rounded-xl bg-accent/30 p-3 text-xs">
                    <div className="flex justify-between text-muted-foreground">
                      <span>Direct Labor Savings:</span>
                      <span className="font-medium text-foreground">{formatInr(roi.annualLaborSavingsInr)} / yr</span>
                    </div>
                    <div className="flex justify-between text-muted-foreground">
                      <span>Velocity Revenue Boost:</span>
                      <span className="font-medium text-foreground">{formatInr(roi.velocityRevenueGainInr)} / yr</span>
                    </div>
                    <div className="flex justify-between border-t border-border/40 pt-1.5 font-bold">
                      <span>Gross Annual Benefit:</span>
                      <span className="text-primary">{formatInr(roi.totalAnnualBenefitInr)}</span>
                    </div>
                    <div className="flex justify-between text-[11px] text-muted-foreground">
                      <span>Less Platform & Integration:</span>
                      <span>- {formatInr(roi.annualPlatformInvestmentInr)}</span>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Right Col: Charts & Sensitivity */}
            {(activeTab === "all" || activeTab === "projection") && (
              <div className={`space-y-6 ${activeTab === "all" ? "lg:col-span-7" : "w-full"}`}>
                {/* 36-Month Cumulative Value Chart */}
                <div className="neu p-6 space-y-4">
                  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between border-b border-border/40 pb-4">
                    <div>
                      <h3 className="font-display text-base font-bold">36-Month Cumulative Financial Trajectory</h3>
                      <p className="text-xs text-muted-foreground">
                        Intersection point illustrates the rapid break-even within {roi.paybackPeriodMonths} months.
                      </p>
                    </div>
                    <div className="flex items-center gap-2 text-xs">
                      <span className="inline-block size-2 rounded-full bg-emerald-500" />
                      <span className="font-semibold text-emerald-600 dark:text-emerald-400">Net Value</span>
                      <span className="inline-block size-2 rounded-full bg-muted-foreground ml-2" />
                      <span className="text-muted-foreground">Investment</span>
                    </div>
                  </div>

                  <div className="h-72 w-full pt-2">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={roi.cumulativeCashflow} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                        <defs>
                          <linearGradient id="benefitGrad" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="var(--color-primary)" stopOpacity={0.4} />
                            <stop offset="95%" stopColor="var(--color-primary)" stopOpacity={0.0} />
                          </linearGradient>
                          <linearGradient id="netGrad" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#10b981" stopOpacity={0.4} />
                            <stop offset="95%" stopColor="#10b981" stopOpacity={0.0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" opacity={0.5} />
                        <XAxis dataKey="month" tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
                        <YAxis
                          tickFormatter={(v) => `${(v / 100000).toFixed(0)}L`}
                          tick={{ fontSize: 11 }}
                          stroke="var(--color-muted-foreground)"
                        />
                        <Tooltip
                          formatter={(val: number, name: string) => [
                            formatInr(val),
                            name === "cumulativeBenefit"
                              ? "Gross Benefit"
                              : name === "netCashflow"
                                ? "Net Cashflow"
                                : "Platform Cost",
                          ]}
                          labelFormatter={(lbl) => `Timeline: ${lbl}`}
                          contentStyle={{
                            backgroundColor: "var(--color-background)",
                            borderColor: "var(--color-border)",
                            borderRadius: "0.75rem",
                            fontSize: "12px",
                          }}
                        />
                        <Area
                          type="monotone"
                          dataKey="cumulativeCost"
                          name="cumulativeCost"
                          stroke="var(--color-muted-foreground)"
                          strokeWidth={1.5}
                          fill="none"
                          strokeDasharray="4 4"
                        />
                        <Area
                          type="monotone"
                          dataKey="netCashflow"
                          name="netCashflow"
                          stroke="#10b981"
                          strokeWidth={2.5}
                          fill="url(#netGrad)"
                        />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </div>

                {/* Sensitivity Analysis Table */}
                <div className="neu p-6">
                  <div className="flex items-center justify-between border-b border-border/40 pb-3">
                    <div>
                      <h3 className="font-display text-base font-bold">Sensitivity Scenarios (Risk Tolerance)</h3>
                      <p className="text-xs text-muted-foreground">
                        Conservative vs Expected vs Aggressive automation models.
                      </p>
                    </div>
                  </div>

                  <div className="mt-4 overflow-x-auto">
                    <table className="w-full text-left text-xs">
                      <thead>
                        <tr className="border-b border-border/40 text-muted-foreground">
                          <th className="pb-2 font-bold">Scenario</th>
                          <th className="pb-2 font-bold">Automation %</th>
                          <th className="pb-2 font-bold">Net Annual (₹)</th>
                          <th className="pb-2 font-bold">Payback</th>
                          <th className="pb-2 font-bold">3-Yr ROI</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20">
                        {roi.sensitivity.map((sc) => (
                          <tr
                            key={sc.scenario}
                            className={sc.scenario === "Expected" ? "bg-primary/5 font-bold" : ""}
                          >
                            <td className="py-2.5">
                              <span
                                className={`rounded px-2 py-0.5 text-[10px] font-bold ${
                                  sc.scenario === "Expected"
                                    ? "bg-primary text-primary-foreground"
                                    : "bg-muted text-muted-foreground"
                                }`}
                              >
                                {sc.scenario}
                              </span>
                            </td>
                            <td className="py-2.5">{sc.automationPct}%</td>
                            <td className="py-2.5 text-emerald-600 dark:text-emerald-400">
                              {formatInr(sc.netAnnualSavingsInr)}
                            </td>
                            <td className="py-2.5">{sc.paybackMonths} mo</td>
                            <td className="py-2.5 font-mono">{sc.threeYearRoi}%</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            )}
          </motion.div>
        )}

        {/* Readiness by Dimension & Transformation Benchmark Cards */}
        {(activeTab === "all" || activeTab === "readiness") && (
          <motion.div
            key={`section-readiness-${activeTab}`}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.2 }}
            className="grid gap-8 lg:grid-cols-2"
          >
            {/* Radar Chart: Readiness */}
            <div className="neu p-6 space-y-4">
              <div className="border-b border-border/40 pb-3">
                <h3 className="font-display text-base font-bold">Digital Transformation Readiness Radar</h3>
                <p className="text-xs text-muted-foreground">
                  Organizational capability score across 6 key enterprise transformation dimensions for {blueprint.domainTitle}.
                </p>
              </div>

              <div className="h-72 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <RadarChart data={blueprint.readinessRadar}>
                    <PolarGrid stroke="var(--color-border)" />
                    <PolarAngleAxis dataKey="dimension" tick={{ fontSize: 10 }} />
                    <Radar
                      name="Your Score"
                      dataKey="score"
                      stroke="var(--color-primary)"
                      fill="var(--color-primary)"
                      fillOpacity={0.3}
                    />
                    <Radar
                      name="Industry Benchmark"
                      dataKey="benchmark"
                      stroke="var(--color-muted-foreground)"
                      fill="none"
                      strokeDasharray="3 3"
                    />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: "var(--color-background)",
                        borderColor: "var(--color-border)",
                        borderRadius: "0.5rem",
                        fontSize: "12px",
                      }}
                    />
                    <Legend />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Benchmark KPI Comparison Cards */}
            <div className="neu p-6 space-y-4">
              <div className="border-b border-border/40 pb-3">
                <h3 className="font-display text-base font-bold">Before vs. After Operational Benchmarks</h3>
                <p className="text-xs text-muted-foreground">
                  Quantified operational performance delta achieved through digital modernization.
                </p>
              </div>

              <div className="space-y-3 pt-1">
                {blueprint.benchmarks.map((bm) => (
                  <div key={bm.metric} className="neu-inset p-3 flex items-center justify-between">
                    <div>
                      <p className="text-xs font-bold text-foreground">{bm.metric}</p>
                      <div className="flex items-center gap-2 mt-1 text-[11px] text-muted-foreground">
                        <span>Before: <strong className="text-foreground/80">{bm.before}</strong></span>
                        <span>→</span>
                        <span>After: <strong className="text-primary">{bm.after}</strong></span>
                      </div>
                    </div>
                    <div className="text-right">
                      <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold text-emerald-600 dark:text-emerald-400">
                        {bm.change}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </div>
    </AppShell>
  );
}
