import { createFileRoute, Link } from "@tanstack/react-router";
import {
  AlertCircle,
  ArrowRight,
  BarChart3,
  Calendar,
  CheckCircle2,
  Clock,
  Coins,
  Copy,
  Download,
  Flame,
  HelpCircle,
  IndianRupee,
  Layers,
  Sparkles,
  TrendingUp,
  Users,
} from "lucide-react";
import { useMemo, useState } from "react";
import {
  Area,
  AreaChart,
  CartesianGrid,
  Legend,
  PolarAngleAxis,
  PolarGrid,
  Radar,
  RadarChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { toast } from "sonner";

import { AppShell } from "@/components/AppShell";
import { ArtifactHeader } from "@/components/ArtifactHeader";
import { CountUp, Reveal, Stagger, StaggerItem } from "@/components/motion/primitives";
import {
  computeHrRoi,
  DEFAULT_HR_ROI_INPUTS,
  HR_BENCHMARKS,
  HR_READINESS_RADAR,
  HrRoiInputs,
} from "@/lib/roi-data";

export const Route = createFileRoute("/workspace/insights")({
  head: () => ({
    meta: [
      { title: "Dynamic ROI & Transformation Dashboard — BizzMitra-AI" },
      {
        name: "description",
        content: "Interactive financial return calculator, 36-month value projection curve, and digital readiness radar.",
      },
      { property: "og:title", content: "Dynamic ROI & Transformation Dashboard — BizzMitra-AI" },
      { property: "og:description", content: "Real-time financial payback modeling and enterprise impact analytics." },
    ],
  }),
  component: InsightsPage,
});

export function InsightsPage() {
  const [inputs, setInputs] = useState<HrRoiInputs>(DEFAULT_HR_ROI_INPUTS);
  const [activeTab, setActiveTab] = useState<"calculator" | "projection" | "readiness">("calculator");

  // Read active workspace context
  const workspaceContext = useMemo(() => {
    if (typeof window === "undefined") return null;
    const raw = localStorage.getItem("bizzmitra.workspaceContext");
    if (!raw) return null;
    try {
      return JSON.parse(raw);
    } catch {
      return null;
    }
  }, []);

  const scenarioName = workspaceContext?.name ?? "TalentCraft HR Consultancy";

  const roi = useMemo(() => computeHrRoi(inputs), [inputs]);

  const formatInr = (val: number) => {
    if (val >= 10000000) return `₹${(val / 10000000).toFixed(2)} Cr`;
    if (val >= 100000) return `₹${(val / 100000).toFixed(2)} L`;
    return `₹${val.toLocaleString("en-IN")}`;
  };

  const copyExecutiveSummary = () => {
    const summary = `EXECUTIVE ROI SUMMARY — ${scenarioName}
==================================================
• Net Annual Savings: ${formatInr(roi.netAnnualSavingsInr)}
• Total Annual Business Value: ${formatInr(roi.totalAnnualBenefitInr)}
• Payback Period: ${roi.paybackPeriodMonths} Months
• 3-Year ROI Multiple: ${roi.threeYearRoiMultiplePct}%
• Recruiter Hours Reclaimed: ${roi.annualHoursSaved.toLocaleString()} hrs/year (${roi.fullTimeEquivalentsReclaimed} FTE equivalent)
• Placement Turnaround Acceleration: ${roi.turnaroundDropPct}% (28 Days down to 9 Days)
• Annual Platform Investment: ${formatInr(roi.annualPlatformInvestmentInr)}
Generated by BizzMitra-AI Transformation Cockpit`;

    navigator.clipboard.writeText(summary);
    toast.success("Executive ROI summary copied to clipboard!");
  };

  const sliders = [
    {
      key: "recruiters",
      label: "Recruiter Squad Size",
      unit: "Recruiters",
      min: 2,
      max: 35,
      step: 1,
      desc: "Full-time consultants currently using spreadsheets",
    },
    {
      key: "monthlyApplicants",
      label: "Monthly Candidate Volume",
      unit: "Applicants",
      min: 50,
      max: 2000,
      step: 25,
      desc: "Resumes received and processed per month",
    },
    {
      key: "hourlyCostInr",
      label: "Recruiter Cost / Hour",
      unit: "₹ / hr",
      min: 200,
      max: 1200,
      step: 25,
      desc: "Blended hourly compensation and overhead",
    },
    {
      key: "spreadsheetHoursPerWeek",
      label: "Manual Admin Time",
      unit: "hrs / week / recruiter",
      min: 5,
      max: 30,
      step: 1,
      desc: "Time lost to WhatsApp, status emails & Excel entry",
    },
    {
      key: "automationRatePct",
      label: "BizzMitra Automation Rate",
      unit: "%",
      min: 30,
      max: 85,
      step: 5,
      desc: "Target workflow automation efficiency",
    },
  ] as const;

  return (
    <AppShell>
      <ArtifactHeader
        id="dashboard"
        kicker="Transformation Cockpit · Step 10"
        title="Financial ROI & Readiness Engine"
      />

      <div className="space-y-8 pb-16">
        {/* Top Hero Banner */}
        <Reveal className="neu p-6 md:p-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <div className="max-w-2xl space-y-2">
              <div className="flex items-center gap-2">
                <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
                  <TrendingUp className="size-3.5" />
                  Live Dynamic ROI Model · Validated Formula
                </span>
                <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
                  Payback: {roi.paybackPeriodMonths} mo
                </span>
              </div>
              <h1 className="font-display text-2xl font-bold tracking-tight sm:text-3xl">
                Transformation Economics: {scenarioName}
              </h1>
              <p className="text-sm leading-relaxed text-muted-foreground">
                Algorithmic financial justification modeling direct recruiter labor savings, capacity revenue expansion, and rapid payback velocity.
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <button
                type="button"
                onClick={copyExecutiveSummary}
                className="neu-sm neu-press flex items-center gap-2 px-3.5 py-2 text-xs font-semibold hover:text-primary"
              >
                <Copy className="size-3.5" />
                Copy Executive Case
              </button>
              <Link
                to="/workspace/map"
                className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground shadow-sm transition hover:opacity-90"
              >
                Inspect Artifact Map
                <ArrowRight className="size-3.5" />
              </Link>
            </div>
          </div>

          {/* Key Executive KPI Cards */}
          <Stagger className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <StaggerItem className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>Net Annual Value</span>
                <IndianRupee className="size-4 text-emerald-500" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold text-emerald-600 dark:text-emerald-400">
                {formatInr(roi.netAnnualSavingsInr)}
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Gross: {formatInr(roi.totalAnnualBenefitInr)}
              </p>
            </StaggerItem>

            <StaggerItem className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>Payback Velocity</span>
                <Clock className="size-4 text-primary" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold">
                {roi.paybackPeriodMonths} <span className="text-base font-normal text-muted-foreground">Months</span>
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Break-even within Q1
              </p>
            </StaggerItem>

            <StaggerItem className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>3-Year Cumulative ROI</span>
                <Flame className="size-4 text-amber-500" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold text-amber-600 dark:text-amber-400">
                {roi.threeYearRoiMultiplePct}%
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Net gain on platform cost
              </p>
            </StaggerItem>

            <StaggerItem className="neu-inset p-4">
              <div className="flex items-center justify-between text-xs font-medium text-muted-foreground">
                <span>Hours Reclaimed / Yr</span>
                <Users className="size-4 text-blue-500" />
              </div>
              <p className="mt-1 font-display text-2xl font-extrabold">
                <CountUp to={roi.annualHoursSaved} /> <span className="text-base font-normal text-muted-foreground">hrs</span>
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                Equiv. to {roi.fullTimeEquivalentsReclaimed} extra recruiters
              </p>
            </StaggerItem>
          </Stagger>
        </Reveal>

        {/* Interactive Main Grid */}
        <div className="grid gap-8 lg:grid-cols-12">
          {/* Left Col: Interactive Sliders (5 cols) */}
          <div className="space-y-6 lg:col-span-5">
            <Reveal className="neu p-6 space-y-6">
              <div className="flex items-center justify-between border-b border-border/40 pb-4">
                <div>
                  <h3 className="font-display text-base font-bold">Dynamic ROI Input Variables</h3>
                  <p className="text-xs text-muted-foreground">
                    Adjust parameters to recalculate savings instantly in real time.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => setInputs(DEFAULT_HR_ROI_INPUTS)}
                  className="text-[11px] font-semibold text-primary hover:underline"
                >
                  Reset Defaults
                </button>
              </div>

              <div className="space-y-5">
                {sliders.map((s) => {
                  const val = inputs[s.key as keyof HrRoiInputs];
                  return (
                    <div key={s.key} className="space-y-1.5">
                      <div className="flex justify-between text-xs">
                        <span className="font-bold text-foreground">{s.label}</span>
                        <span className="font-mono font-bold text-primary">
                          {val.toLocaleString("en-IN")} {s.unit}
                        </span>
                      </div>
                      <input
                        type="range"
                        min={s.min}
                        max={s.max}
                        step={s.step}
                        value={val}
                        onChange={(e) =>
                          setInputs((prev) => ({ ...prev, [s.key]: Number(e.target.value) }))
                        }
                        className="w-full accent-primary cursor-pointer"
                      />
                      <p className="text-[10px] text-muted-foreground">{s.desc}</p>
                    </div>
                  );
                })}
              </div>

              {/* Breakdown Breakdown */}
              <div className="space-y-2 rounded-xl bg-accent/30 p-3 text-xs">
                <div className="flex justify-between text-muted-foreground">
                  <span>Direct Labor Savings:</span>
                  <span className="font-medium text-foreground">{formatInr(roi.annualLaborSavingsInr)} / yr</span>
                </div>
                <div className="flex justify-between text-muted-foreground">
                  <span>Velocity Revenue Boost:</span>
                  <span className="font-medium text-foreground">{formatInr(roi.velocityRevenueGainInr)} / yr</span>
                </div>
                <div className="flex justify-between border-t border-border/40 pt-1.5 font-bold">
                  <span>Gross Annual Benefit:</span>
                  <span className="text-primary">{formatInr(roi.totalAnnualBenefitInr)}</span>
                </div>
                <div className="flex justify-between text-[11px] text-muted-foreground">
                  <span>Less Platform & Integration:</span>
                  <span>- {formatInr(roi.annualPlatformInvestmentInr)}</span>
                </div>
              </div>
            </Reveal>
          </div>

          {/* Right Col: Charts & Sensitivity (7 cols) */}
          <div className="space-y-6 lg:col-span-7">
            {/* 36-Month Cumulative Value Chart */}
            <Reveal className="neu p-6 space-y-4">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between border-b border-border/40 pb-4">
                <div>
                  <h3 className="font-display text-base font-bold">36-Month Cumulative Financial Trajectory</h3>
                  <p className="text-xs text-muted-foreground">
                    Intersection point illustrates the rapid break-even within {roi.paybackPeriodMonths} months.
                  </p>
                </div>
                <div className="flex items-center gap-2 text-xs">
                  <span className="inline-block size-2 rounded-full bg-emerald-500" />
                  <span className="font-semibold text-emerald-600 dark:text-emerald-400">Net Value</span>
                  <span className="inline-block size-2 rounded-full bg-muted-foreground ml-2" />
                  <span className="text-muted-foreground">Investment</span>
                </div>
              </div>

              <div className="h-72 w-full pt-2">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={roi.cumulativeCashflow} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                    <defs>
                      <linearGradient id="benefitGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="var(--color-primary)" stopOpacity={0.4} />
                        <stop offset="95%" stopColor="var(--color-primary)" stopOpacity={0.0} />
                      </linearGradient>
                      <linearGradient id="netGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#10b981" stopOpacity={0.4} />
                        <stop offset="95%" stopColor="#10b981" stopOpacity={0.0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" opacity={0.5} />
                    <XAxis dataKey="month" tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
                    <YAxis
                      tickFormatter={(v) => `${(v / 100000).toFixed(0)}L`}
                      tick={{ fontSize: 11 }}
                      stroke="var(--color-muted-foreground)"
                    />
                    <Tooltip
                      formatter={(val: number, name: string) => [
                        formatInr(val),
                        name === "cumulativeBenefit"
                          ? "Gross Benefit"
                          : name === "netCashflow"
                            ? "Net Cashflow"
                            : "Platform Cost",
                      ]}
                      labelFormatter={(lbl) => `Timeline: ${lbl}`}
                      contentStyle={{
                        backgroundColor: "var(--color-background)",
                        borderColor: "var(--color-border)",
                        borderRadius: "0.75rem",
                        fontSize: "12px",
                      }}
                    />
                    <Area
                      type="monotone"
                      dataKey="cumulativeCost"
                      name="cumulativeCost"
                      stroke="var(--color-muted-foreground)"
                      strokeWidth={1.5}
                      fill="none"
                      strokeDasharray="4 4"
                    />
                    <Area
                      type="monotone"
                      dataKey="netCashflow"
                      name="netCashflow"
                      stroke="#10b981"
                      strokeWidth={2.5}
                      fill="url(#netGrad)"
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </Reveal>

            {/* Sensitivity Analysis Table */}
            <Reveal className="neu p-6">
              <div className="flex items-center justify-between border-b border-border/40 pb-3">
                <div>
                  <h3 className="font-display text-base font-bold">Sensitivity Scenarios (Risk Tolerance)</h3>
                  <p className="text-xs text-muted-foreground">
                    Conservative vs Expected vs Aggressive automation models.
                  </p>
                </div>
              </div>

              <div className="mt-4 overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="border-b border-border/40 text-muted-foreground">
                      <th className="pb-2 font-bold">Scenario</th>
                      <th className="pb-2 font-bold">Automation %</th>
                      <th className="pb-2 font-bold">Net Annual (₹)</th>
                      <th className="pb-2 font-bold">Payback</th>
                      <th className="pb-2 font-bold">3-Yr ROI</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border/20">
                    {roi.sensitivity.map((sc) => (
                      <tr
                        key={sc.scenario}
                        className={sc.scenario === "Expected" ? "bg-primary/5 font-bold" : ""}
                      >
                        <td className="py-2.5">
                          <span
                            className={`rounded px-2 py-0.5 text-[10px] font-bold ${
                              sc.scenario === "Expected"
                                ? "bg-primary text-primary-foreground"
                                : "bg-muted text-muted-foreground"
                            }`}
                          >
                            {sc.scenario}
                          </span>
                        </td>
                        <td className="py-2.5">{sc.automationPct}%</td>
                        <td className="py-2.5 text-emerald-600 dark:text-emerald-400">
                          {formatInr(sc.netAnnualSavingsInr)}
                        </td>
                        <td className="py-2.5">{sc.paybackMonths} mo</td>
                        <td className="py-2.5 font-mono">{sc.threeYearRoi}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Reveal>
          </div>
        </div>

        {/* Readiness by Dimension & Transformation Benchmark Cards */}
        <div className="grid gap-8 lg:grid-cols-2">
          {/* Radar Chart: Readiness */}
          <Reveal className="neu p-6 space-y-4">
            <div className="border-b border-border/40 pb-3">
              <h3 className="font-display text-base font-bold">Digital Transformation Readiness Radar</h3>
              <p className="text-xs text-muted-foreground">
                Organizational capability score across 6 key enterprise transformation dimensions.
              </p>
            </div>

            <div className="h-72 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <RadarChart data={HR_READINESS_RADAR}>
                  <PolarGrid stroke="var(--color-border)" />
                  <PolarAngleAxis dataKey="dimension" tick={{ fontSize: 10 }} />
                  <Radar
                    name="TalentCraft Score"
                    dataKey="score"
                    stroke="var(--color-primary)"
                    fill="var(--color-primary)"
                    fillOpacity={0.3}
                  />
                  <Radar
                    name="Industry Benchmark"
                    dataKey="benchmark"
                    stroke="var(--color-muted-foreground)"
                    fill="none"
                    strokeDasharray="3 3"
                  />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "var(--color-background)",
                      borderColor: "var(--color-border)",
                      borderRadius: "0.5rem",
                      fontSize: "12px",
                    }}
                  />
                  <Legend />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </Reveal>

          {/* Benchmark KPI Comparison Cards */}
          <Reveal className="neu p-6 space-y-4">
            <div className="border-b border-border/40 pb-3">
              <h3 className="font-display text-base font-bold">Before vs. After Operational Benchmarks</h3>
              <p className="text-xs text-muted-foreground">
                Quantified operational performance delta achieved through TalentCraft digital modernization.
              </p>
            </div>

            <div className="space-y-3 pt-1">
              {HR_BENCHMARKS.map((bm) => (
                <div key={bm.metric} className="neu-inset p-3 flex items-center justify-between">
                  <div>
                    <p className="text-xs font-bold text-foreground">{bm.metric}</p>
                    <div className="flex items-center gap-2 mt-1 text-[11px] text-muted-foreground">
                      <span>Before: <strong className="text-foreground/80">{bm.before}</strong></span>
                      <span>→</span>
                      <span>After: <strong className="text-primary">{bm.after}</strong></span>
                    </div>
                  </div>
                  <div className="text-right">
                    <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold text-emerald-600 dark:text-emerald-400">
                      {bm.change}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </Reveal>
        </div>
      </div>
    </AppShell>
  );
}
